### ISSUE TITLE
min_expr in plot_genes_by_pseudotime has incorrect log transformation

### ISSUE THREAD

**Issue by ctrapnell** [cole-trapnell-lab/monocle-release#1]
From Kieran Campbell:

In the function plot_genes_in_pseudotime, the following is used as the predicted expression curve:

res <- 10^(predict(vg, type = "response"))
res[res < log10(min_expr)] <- log10(min_expr)

where vg is the vgam model fit and min_expr is the minimum expression cut-off (default 0.1). However, res has been transformed back to the non-logged scale but is censored on the log-scale, meaning the cut-off in most plots is actually far below where it should be.

**Comment by Xiaojieqiu** [comment]
this issue has been addressed a while ago with the genSmoothCurves and correct censoring
