### ISSUE TITLE
order cells

### ISSUE THREAD

**Issue by xnaer** [cole-trapnell-lab/monocle-release#101]
Hi Monocle group,

Can I specify the beginning, middle, and the ending of the cells to order?
![image](https://user-images.githubusercontent.com/30447801/34628752-86e71fd6-f233-11e7-8879-14ff00068b30.png)
In this plot, I want to choose the green one as the beginning and the red one as the ending. How can I access? Thx.

Bests,

Na

**Comment by Xiaojieqiu** [comment]
orderCells function allow you to set the root_state. You can set the `root_state = 1` to order the cell
