### ISSUE TITLE
could not find function "plot_complex_cell_trajectory"

### ISSUE THREAD

**Issue by SpunkSpark** [cole-trapnell-lab/monocle-release#104]
>options(repr.plot.width=6, repr.plot.height=4)
> plot_complex_cell_trajectory(URMM_all_fig1b[, ], color_by = 'cluster', show_branch_points = T, cell_size = 0.5, cell_link_size = 0.3) + facet_wrap(~Type, nrow = 1) + scale_size(range = c(0.2, 0.2)) +
+     theme(axis.text.x = element_text(angle = 30, hjust = 1)) + scale_color_manual(values = cluster_cols, name = "cluster")
Error in plot_complex_cell_trajectory(URMM_all_fig1b[, ], color_by = "cluster",  : 
  could not find function "plot_complex_cell_trajectory"

How can I solve this problem? thank you for your help

**Comment by Xiaojieqiu** [comment]
please ensure you updated monocle to monocle_2.6.3
