### ISSUE TITLE
error in plot_genes_branched_heatmap

### ISSUE THREAD

**Issue by cynthiazhou1005** [cole-trapnell-lab/monocle-release#105]
I have encountered an error trying to plot_genes_branched_heatmap:

Error in vstExprs(new_cds, expr_matrix = BranchA_exprs) : 
  Error: No dispersion model named 'blind'. You must call estimateSizeFactors(...,dispModelName='blind') before calling this function.

I'm analyzing the data based on FPKM and I had no problem getting the pseudotime heatmap....
Any advice?
Thank you,
Wen

**Comment by Xiaojieqiu** [comment]
please ensure the `expressionFamily` you used for the data is `tobit` model if you are using FPKM. otherwise you need to run estimateSizeFactor and estimateDispersion function
