### ISSUE TITLE
Question: What parameters can be used to make points closer to the main skeleton?

### ISSUE THREAD

**Issue by qrzhang** [cole-trapnell-lab/monocle-release#107]
Hi, 

I am wondering how can I make points closer to the main skeleton of a pseudotime tree as figures in your tutorial? The comparison between my own figure and your figure in Olsson Dataset Analysis tutorial is attached below. 

Thanks a lot. 

![artboard 3](https://user-images.githubusercontent.com/19705471/35190382-0bef19ae-fe9b-11e7-984d-854b047f3e23.png)

**Comment by Xiaojieqiu** [comment]
Hi, 

If you set `param.gamma` bigger, for example `param.gamma = 100`, it will impose strong clustering effect on the tree and the cells will be shrinked to the principal points. You may have also found the code in the tutorial used that, for example
```
pData(URMM_all_abs)[colnames(URMM_all_fig1b), 'paper_cluster'] <- as.character(pData(URMM_all_fig1b)[, 'cluster'])

URMM_all_abs <- setOrderingFilter(URMM_all_abs, ordering_genes = URMM_ordering_genes)
URMM_all_abs <- reduceDimension(URMM_all_abs, verbose = F, scaling = T, maxIter = 100, norm_method = 'log', max_components = 4, param.gamma = 100, lambda = 14 * ncol(URMM_all_fig1b)) 
URMM_all_abs <- orderCells(URMM_all_abs)
options(repr.plot.width=6, repr.plot.height=5)
plot_cell_trajectory(URMM_all_abs, color_by = 'Type')
options(repr.plot.width=8, repr.plot.height=8)
plot_cell_trajectory(URMM_all_abs, color_by = 'Type') + facet_wrap(~paper_cluster)
```

Please see a detail description about all parameters in Monocle 2 algorithm in `supplementary figure 13` of the published paper (https://media.nature.com/original/nature-assets/nmeth/journal/v14/n10/extref/nmeth.4402-S1.pdf)
