### ISSUE TITLE
dispersionTable not found

### ISSUE THREAD

**Issue by yzqheart** [cole-trapnell-lab/monocle-release#12]
Hello,

I installed monocle through bioconductor. However, when I ran the code in the vignette

disp_table <- dispersionTable(HSMM)

An error occurred 
Error: could not find function "dispersionTable"

My R is version 3.2.5

Can you help me to fix this ?

**Comment by Xiaojieqiu** [comment]
dispersionTable has been exported. 

I suppose this is also resolved and will close this issue
