### ISSUE TITLE
Earlier versions of monocle

### ISSUE THREAD

**Issue by JoachimLu** [cole-trapnell-lab/monocle-release#120]
I used an earlier version of monocle (2.2.0) or even earlier for some of my analysis. After updating monocle, I can not reproduce my data. In order to find out the reasons for this I would like to re-install version 2.2.0, but I can not find it anywhere. On bioconductor if I go to earlier versions there is only the newest version available.

**Comment by JoachimLu** [comment]
Correction, I am actually looking for monocle version 2.4.0.

**Comment by ctrapnell** [comment]
Monocle 2.4.0 was part of the Bioconductor 3.5 release: 

https://www.bioconductor.org/packages/3.5/bioc/html/monocle.html

**Comment by JoachimLu** [comment]
Thank you very much!
