### ISSUE TITLE
Identifying multiple parallel trajectories with monocle?

### ISSUE THREAD

**Issue by dhb2128** [cole-trapnell-lab/monocle-release#125]
Hi,

I've been analyzing some single-cell data with monocle 2. For these cells, we have a general sense of the markers for precursors, immature cells, and mature cells. For the most part, the known trajectory matches up with what we see with the pseudotime values, but there also seem to be some quirks. For starters, although the DDRtree embedding often produces multiple branches, these separate branches do not make biological sense to us. We find relatively few DE genes between branches, and the cells at the end of separate branches do not match the types of clusters we've previously identified.

One idea we had was that this might actually be the result of trying to embed two parallel trajectories. In other words, there might actually be subclasses of precursors that produce separate immature cells that produce separate mature cells rather than a single type of precursors that produces multiple classes of immature/mature cells. 

Do you know of any situations where people have encountered similar problems? Does monocle have a way to distinguish between the possibility of having multiple parallel trajectories rather than a single cell type that develops into a single or multiple branches? Are there any good metrics to evaluate the quality of embedding or distinguish between these possibilities?

Looking forward to hearing your suggestions!

**Comment by Xiaojieqiu** [comment]
Hi David, 

Thanks for asking this important question regarding to multiple types of precursors and parallel trajectories. Actually this is one of the questions I am working on right now. We are planning to release a update of Monocle which enables building multiple trajectories at once. So stay tuned... For now, my suggestion is to first run a clustering analysis (using clusterCells function with either the `densityPeak` or `louvain` clustering method) and figure out the clusters related to each potential trajectory with some manual inspection and then run DDRTree on each trajectory separately. Hope this helps

**Comment by dhb2128** [comment]
Thanks for your reply! I look forward to seeing what progress you all make.
