### ISSUE TITLE
using pq_helper

### ISSUE THREAD

**Issue by zuta-osa77** [cole-trapnell-lab/monocle-release#127]
Hi, 

I'm interested in using pq_helper to generate some PQ trees from MST's that I have in **igraph**. I've loaded just the functions **get_next_node_id** and **pq_helper** in an attempt to do so. I have two questions

a) Is it ok to use the functions this way and 

b) if so, how do you reconstruct the PC ordering ensemble from the single $subtree slot output of pq_helper? 

Thanks!
zo

**Comment by Xiaojieqiu** [comment]
to briefly answer your question: 
a) yes that is tree
b) you need to look at the `extract_good_branched_ordering`

However, if you are only interested in testing the performance or so, please check the procedure for pseudotime assignment in the current default DDRTree based ordering method. The functions you are pointing out are from our Monocle 1 algorithm and will be eventually depreciated.
