### ISSUE TITLE
difference between ModelFormulaStr

### ISSUE THREAD

**Issue by camilliano** [cole-trapnell-lab/monocle-release#131]
Hello,
can someone please explain to me what is the difference between:
`residualModelFormulaStr`
`fullModelFormulaStr`
`reduceModelFormulaStr`.

`residualModelFormulaStr` is used in order to remove effects from data before clustering, but for the last two one, I don't get it....

Thanks for your help!
Camille

**Comment by Xiaojieqiu** [comment]
Thanks for asking @camilliano ! Monocle uses generalized linear models to fit the data and apply likelihood ratio test to perform differential gene expression tests. For likelihood ratio test, it tries to compare two models (a null model and an alternative model). The `fullModelFormulaStr` and  `reduceModelFormulaStr` correspond to the alternative model and null model respectively.
