### ISSUE TITLE
Error in as.igraph.vs(graph, to) : Invalid vertex names

### ISSUE THREAD

**Issue by brianpenghe** [cole-trapnell-lab/monocle-release#134]
I was using BEAM. But I'm trying to analyze a different list of genes (transcription factors, HSMMTF_major) not necessarily included in the original matrix (1000 high dispersion genes) used to construct the minSpanningTree. What I did was to build a two variables, one for the 1000 genes to construct the tree and one for the transcription factors to do BEAM. I manually copied the attributes from the 1000 gene variable (HSMM_major) to the one of Transcription factors. But BEAM doesn't work on it.

Here are the codes and error message:
> HSMMTF_major@reducedDimS=HSMM_major@reducedDimS
> HSMMTF_major@reducedDimW=HSMM_major@reducedDimW
> HSMMTF_major@reducedDimA=HSMM_major@reducedDimA
> HSMMTF_major@reducedDimK=HSMM_major@reducedDimK
> HSMMTF_major@minSpanningTree=HSMM_major@minSpanningTree
> HSMMTF_major@cellPairwiseDistances=HSMM_major@cellPairwiseDistances
> HSMMTF_major@phenoData=HSMM_major@phenoData
> HSMMTF_major@dim_reduce_type=HSMM_major@dim_reduce_type
> HSMMTF_major@.__classVersion__=HSMM_major@.__classVersion__
> BEAM_res <- BEAM(HSMMTF_major,branch_point = 1, cores = 1)
Error in as.igraph.vs(graph, to) : Invalid vertex names

**Comment by Xiaojieqiu** [comment]
Hi @brianpenghe actually don't need to separate the data into two `cds`. You can simply set the ordering gene (using `setOrderingFilter` function) for the entire dataset with the 1k top dispersion gene and then reconstruct the trajectory. Then you can apply BEAM for any genes (or all genes in your data) of your interests.  

Let me if this makes sense.

**Comment by brianpenghe** [comment]
Thanks @Xiaojieqiu  That is indeed an easy fix.
