### ISSUE TITLE
Undefined columns in differentialGeneTest

### ISSUE THREAD

**Issue by TobiasBB** [cole-trapnell-lab/monocle-release#135]
Dear Monocle team,

Thank you very much for creating and maintaining monocle! I have suddenly run into an issue with the differentialGeneTest, which was working without issues in my code earlier. If have unfortunately been unsuccessful in resolving the issue my self, do you have an idea what could be the issue?

When running "differentialGeneTest(ec_cds, fullModelFormulaStr = '~Clusters')" i get an error message "Error in `[.data.frame`(pd, , i) : undefined columns selected". This goes both with and without specifying marker genes for the cds.

![diffgenetest error](https://user-images.githubusercontent.com/38525166/38983753-6bc3fc22-43c5-11e8-9d5d-b5a00cfefb06.png)

Best,
Tobias

**Comment by mtekman** [comment]
I am seeing this error. Can I ask what the solution to this was?

**Comment by novikovdan** [comment]
@TobiasBB @mtekman me too, help me please

**Comment by TobiasBB** [comment]
Yes - what I found was that you need to reduceDimensions using DDRtree method (reduceDimension(cds, max_components = 2, method = 'DDRTree')) and orderCells before being able to run differentialGeneTest using fullModelFormulaStr = "~sm.ns(Pseudotime)", which was my main issue.

At some point I had issues running differentialGeneTest on clusters and never really pinpointed the issue (it should work after running reduceDimensions using tSNE as method, and subsequently clusterCells). After re-writing the script it worked for me, despite not changing anything.

I hope this helps somewhat!

**Comment by mtekman** [comment]
reducing via DDRTree seems to work, thank you!

**Comment by tilofrei** [comment]
Reading the tutorial I believe the variables referred to in `fullModelFormulaString` have to be available (see: `print(head(pData(data.monocle)))` for available variables).

In your case maybe you didn't do the clustering step to yield the variable _Cluster_? 
```
HSMM_myo <- clusterCells(HSMM_myo, verbose = F)
```
from: [monocle tutorial](http://cole-trapnell-lab.github.io/monocle-release/docs/#alternative-choices-for-ordering-genes)

**Comment by samadelk** [comment]
> Reading the tutorial I believe the variables referred to in `fullModelFormulaString` have to be available (see: `print(head(pData(data.monocle)))` for available variables).
> 
> In your case maybe you didn't do the clustering step to yield the variable _Cluster_?
> 
> ```
> HSMM_myo <- clusterCells(HSMM_myo, verbose = F)
> ```
> 
> from: [monocle tutorial](http://cole-trapnell-lab.github.io/monocle-release/docs/#alternative-choices-for-ordering-genes)

same here I had to specify a variable from pData (clusters) to make it working !
