### ISSUE TITLE
CellTypeHierarchy Issues

### ISSUE THREAD

**Issue by tjkwon** [cole-trapnell-lab/monocle-release#14]
When I try to run the classifyCells function as part of the CellTypeHierarchy analysis (section 3.1 in the vignette), I get the following error:

Error in if (type_res[cell_name] == TRUE) next_nodes <- c(next_nodes,  : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
Deprecated, use tibble::rownames_to_column() instead. 

I am using:
- R: 3.3.1
- monocle: 2.2.0
- dplyr: 0.5.0

**Comment by nikhil** [comment]
Hey tjkwon,

I had a similar issue, but I found that I was not typing in the correct gene_short_name. You need to make sure the gene_short_name exists:
```R
which(fData(HSMM)$gene_short_name == 'Sox9')
```

**Comment by tjkwon** [comment]
Dear Nikhil,

Somehow, this email escaped me until today. Thanks for the tip! I will see how it looks on my data.

Regards,
Andrew

**Comment by fancycoding** [comment]
Hi Nikhil,
I came across the same issue. Have you figured it out?
Best,
Jia

**Comment by nikhil** [comment]
Hey fancycoding,
Yeah, I got this error when the gene name was misspelled.
Sincerely,
Nikhil Kumar

**Comment by brianpenghe** [comment]
Thanks for this issue.
If only Monocle had a Matlab version it would be easier for me.

**Comment by truittll** [comment]
It turns out I was doing the same thing (misspelling). After I fixed the misspelling however I got a new error 
 "Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : 
  invalid character indexing"

Any ideas?
