### ISSUE TITLE
Extract genes from every stable state

### ISSUE THREAD

**Issue by jgarces02** [cole-trapnell-lab/monocle-release#144]
Hi there, 

I'm trying to extract those characteristic genes which are defining every cell cluster in a trajectory plot... in addition to extract specific-cluster cells, is there any possibility to get also those defining genes?

Thanks in advance. Best regards.

**Comment by Xiaojieqiu** [comment]
This issue is related to #91 . We will try to provide the functionality for it for the next release soon

**Comment by jgarces02** [comment]
Thanks then!
