### ISSUE TITLE
Extracting row names from plot_genes_branched_heatmap

### ISSUE THREAD

**Issue by ksr2018** [cole-trapnell-lab/monocle-release#147]
Hello, 
I recently started using monocle 2 and have very minimal experience with R.
Can someone please help me figure out how to extract row names / gene names from the plot_genes_branched_heatmap. currently, the heatmaps I am generating have several genes/rows and its not readable in the plot. I would like to extract these into a csv file.
Thanks!

**Comment by Xiaojieqiu** [comment]
if you set r`eturn_heatmap = TRUE` in the `plot_genes_branched_heatmap` function. you should be able to extract all information used to create the heatmap

**Comment by ksr2018** [comment]
Thank you!
