### ISSUE TITLE
ImportCDS does not set ordering filter

### ISSUE THREAD

**Issue by efheuston** [cole-trapnell-lab/monocle-release#148]
Hi Monocle!

I'm trying to import a Seurat object using importCDS(seuratObject, import_all=TRUE), but it won't import the var.genes.

><img width="545" alt="screen shot 2018-05-22 at 10 07 52 am" src="https://user-images.githubusercontent.com/27958036/40367734-19c332d8-5da8-11e8-9301-e79733a69af0.png">

However, it works if I use setOrderingFilter, it works.

><img width="545" alt="screen shot 2018-05-22 at 10 08 19 am" src="https://user-images.githubusercontent.com/27958036/40367976-a6663bf4-5da8-11e8-9fd7-c47ceaf18cd7.png">

I'm worried I'm not using importCDS correctly and might be messing up data in other slots. I'd appreciate any advice.

Thanks!

E

**Comment by Xiaojieqiu** [comment]
hi @efheuston I think you are doing the right thing. We had a bug in the `importCDS` function and the variable genes should really be set as ordering genes. Thanks for pointing out this. We will fix this bug in a release scheduled in a couple weeks.

**Comment by efheuston** [comment]
Thanks so much, and I'll keep an eye out for the new release!
