### ISSUE TITLE
Difference between monocle 2.2 and 2.6

### ISSUE THREAD

**Issue by AnnaB160** [cole-trapnell-lab/monocle-release#149]
Hello,
I can not find the release log. I am getting different  trajectories (mostly an extra small branch)  when I run monocle 2.2 versus monocle 2.6 and I would like to figure out why that happens.

Thanks a lot

**Comment by Xiaojieqiu** [comment]
the NEWS file includes some information about the new features in each monocle release (https://github.com/cole-trapnell-lab/monocle-release/blob/master/NEWS). The extra small branch may be related to a few bug fixes in preprocessing the data and DDRTree package. Normally small insignificant branches may just result from noise from the dataset though. If that is the case, you probably can ignore them

**Comment by AnnaB160** [comment]
Thanks
