### ISSUE TITLE
BEAM function never finishes

### ISSUE THREAD

**Issue by IStevant** [cole-trapnell-lab/monocle-release#15]
Dear developers,

I ran Monocle2 on a RPKM matrix of 400 single-cells. RPKMs were calculated with an in-house script proper to my lab (I don't own the code). I estimated the RNA counts with relative2abs() then I generated the dataset with negbinomial().
I successfully ordered by pseudotime the cells with supervised and unsupervised methods and now I would like to identify the genes explaining the branching using BEAM().

I ran BEAM on the lung dataset in a minute but with my data, BEAM function runs but never ends. I let my computer on all the week-end on just to see and it was still running after 3 days.

I created a test dataset from my data (50 randomly picked cells) and I've got the same issue.

Here is my script:
https://github.com/IStevant/XY-mouse-gonad-scRNA-seq/blob/master/Scripts/test_monocle2.R

And here is the test dataset:
https://github.com/IStevant/XY-mouse-gonad-scRNA-seq/blob/master/Data/sample_test_monocle2.csv

I hope you will find out what's going wrong.

**Comment by Xiaojieqiu** [comment]
Hey there, 

I tried to run your script but it seems you didn't save the RData file (sample_test_monocle2.csv is a csv file). So I can not reproduce your problem. 

But I would like to suggest you to run differential gene expression test, including BEAM, in monocle with expression family set as  negbinomial.size(). negbinomial() is often very slow when your data has a lot zero value. This is a numerical issues from VGAM. 

Let me know if that helps

**Comment by IStevant** [comment]
Hi,

sorry, I didn't double check the import part of the script... I just fixed it:
https://github.com/IStevant/XY-mouse-gonad-scRNA-seq/blob/master/Scripts/test_monocle2.R

I also created a Robj of the monocle CellDataSet if you prefer:
https://github.com/IStevant/XY-mouse-gonad-scRNA-seq/blob/master/Data/monocle_obj_test_CellDataSet.Robj

I also tried differentialGeneTest() on the whole transcriptome with negbinomial() with no issue, and I ran BEAM with negbinomial.size() but it still stays stuck.

**Comment by Xiaojieqiu** [comment]
So I found the issues results from the fact that your data include a lot genes expressed in very few cells or no cells at all. BEAM test relies on spline curve fitting with vglm across two cell fates (A paper accepted by Nature Methods will be online next Monday describing this approach, please refer to that paper for details). BEAM test thus has more restriction on data than the two group test often used in differentialGeneTest. In the case where you only have a few cells (or no cells) expressing that gene, VGLM cannot fit the data and will thus hang on forever. 

We will fix this issue in next release by avoiding test on those genes.

For now, you can select only genes expressed at least 5 cells or so, for example: 
```
sampleCells <- detectGenes(sampleCells)
sampleCells_subset <- sampleCells[fData(sampleCells)$num_cells_expressed > 5, ]
BEAM_res <- BEAM(sampleCells_subset, branch_point=1, cores = 1)

BEAM_res <- BEAM_res[order(BEAM_res$qval),]
BEAM_res <- BEAM_res[,c("genes", "pval", "qval")]

plot_genes_branched_heatmap(sampleCells_subset[row.names(subset(BEAM_res, qval < 1e-4)),],
                            branch_point = 1,
                            num_clusters = 4,
                            cores = 1,
                            use_gene_short_name = T,
                            show_rownames = T)
```
Here is the resulting branched heatmap: 
   ![screen shot 2017-01-19 at 1 14 03 pm](https://cloud.githubusercontent.com/assets/7456281/22125434/84ef13e6-de48-11e6-8924-d15d60d22937.png)

**Comment by IStevant** [comment]
Hi,

I tested your solution:
sampleCells_subset <- sampleCells[fData(sampleCells)$num_cells_expressed > 5, ]

I had to increase the number of cell genes are detected in to compute faster but the results are just beautiful !

Thanks a lot for the help, I'm looking forward to the paper.

**Comment by Xiaojieqiu** [comment]
here is the link to the paper, btw: http://www.nature.com/nmeth/journal/vaop/ncurrent/full/nmeth.4150.html
