### ISSUE TITLE
How to specify fullModelFormulaStr

### ISSUE THREAD

**Issue by cakirb** [cole-trapnell-lab/monocle-release#151]
Hello,
There is no guideline how to specify fullModelFormulaStr/reducedModelFormulaStr in differentialGeneTest. In the tutorial, it says "~Media", but it is not clear what it is and how it should be specified. I could not find any source about that. 

Thanks...

**Comment by bc2zb** [comment]
It's from R's formula functionality. 

https://www.rdocumentation.org/packages/stats/versions/3.5.0/topics/formula

**Comment by cakirb** [comment]
For Monocle and CellDataSet object, what can I type into there? I’ve seen some examples, but I couldn’t understand how it pulls data from the object according to the formula.

**Comment by bc2zb** [comment]
You should be able to pass in any column names of the pData of your CellDataSet. Just be sure to wrap it in quotes and include the "~". For example:

````
> colnames(pData(updated_gbm_cds))
 [1] "barcode"                         "Size_Factor"                     "num_genes_expressed"             "Cluster"                         "peaks"                           "halo"                           
 [7] "delta"                           "rho"                             "nearest_higher_density_neighbor" "Pseudotime"                      "State"
````
This means I can use any of those values in my fullModelFormulaStr calls. If you look at the documentation and source code for BEAM, you'll see how they specify the formulas. If you want a deep dive are R formula notation, the [limma package](http://bioconductor.org/packages/release/bioc/html/limma.html) is actually a great package to review. Particularly, Chapter 9.

**Comment by cakirb** [comment]
@bc2zb Your reply is very helpful. Thank you very much!!
