### ISSUE TITLE
Branch point issue

### ISSUE THREAD

**Issue by MichaelStreuber** [cole-trapnell-lab/monocle-release#167]
Hi,

I run a Monocle script in unsupervised mode. In my trajectory I saw that for the second state (in orange below) there was no branch visible at branch point Nr. 4 going somewhere.

![image](https://user-images.githubusercontent.com/34674278/42692013-6e08cdbe-86aa-11e8-87f0-c5d2dd0f2159.png)

1) Does it mean that state 2 is lying on the branch point Nr. 4?? Is that an indication, that something went wrong?

2) Maybe I missed it in another issue report, but why is the first coming branch point annotated with Nr. 4 instead of e.g. Nr. 1?

Best wishes and thank you for any kind of support!
Michael

**Comment by Xiaojieqiu** [comment]
Hi @MichaelStreuber , thanks for using Monocle! To answer your question: 
1. It seems like that the state 2 branches off from branch point 4. You cannot see the branch backbone (principal graph branch) on your plot but it could be that the branch is short, like the one related to branch 1. Also, are you setting `max_component` to be something larger than 2?If that is the case, you may see the principal graph in a different dimension more clearly. Note that the recent release Monocle 3alpha includes a functionalities to visualize trajectory, etc. in 3D and the trajectory reconstruct algorithms are dramatically improved. Please see the this tutorial for more details: http://cole-trapnell-lab.github.io/monocle-release/monocle3/. More tutorials and updates will be released soon! 
2. The branch assignment and the branch point index assignment are not necessarily to "match" each other. That is, we assign branch state based on a deep-first search of the principal graph and assign a new state every time we see a branch point along this search while for the index for the branch point is only assigned during the trajectory plotting process. I will try to match them up in the next release.

**Comment by MichaelStreuber** [comment]
Hi Xiaojieqiu,

Thanks a lot for this very quick response. Concerning your question I used max_compenents = 10, because for lower/higher max_components there were too many branch points and states lying over each other.
Thank you for this detailed explanation!!

Best,
Michael
