### ISSUE TITLE
Error in estimateDispersions()

### ISSUE THREAD

**Issue by anjanbharadwaj** [cole-trapnell-lab/monocle-release#170]
Whenever I try to run the estimateDispersions() function on the cell data set, I get several warnings of
"In log(ifelse(y == 0, 1, y/mu)) : NaNs produced". This later turns into an error (I assume), when I try to run the differentialGeneTest function, as I get the error: `Error in [.data.frame(pd, , i) : undefined columns selected`. 

Any ideas on what might be happening?

**Comment by BioLaoXu** [comment]
i had account thie problem, I've worked it out by transposing my count matrix,and then CreateSeuratObject
