### ISSUE TITLE
Removing unwanted source of variation before clustering and pseudo-time analysis

### ISSUE THREAD

**Issue by ravipatel4** [cole-trapnell-lab/monocle-release#178]
Hello,

I am interested in removing unwanted source of variation from my raw data before proceeding for clustering and pseudo-time analysis. Is there any option in monocle to regress out nUMI-based variation between cells (as done in Seurat)? Or what would you recommend how should I do this?

If you care, the reason I am interested in doing this is because, my cells seems to have two sub-groups: cells with higher total UMI counts (nUMI) and cells with lower nUMI. When I try to cluster the cells, my cells first cluster in two groups, which is solely based on nUMI. I want to avoid the effect of nUMI on my clustering.

Thank you in advance in anticipation of your help.

Best,
Ravi

**Comment by Xiaojieqiu** [comment]
The size factor calculated from `estimateSizeFactors` (required before performing downstream analysis) should have already taken care of the difference in the library size. So it is puzzling to me why the clustering still results in two clusters corresponding to the two groups of cells with different nUMI. Maybe those cells are biologically distinct? 

Anyway, Monocle indeed supports ways to regress out unwanted variations, please see the `residualModelFormulaStr` argument in `preprocessCDS function (if you are using Monocle 3 alpha) or in `reduceDimension` (if you are using Monocle 2 installed from bioconductor). For example, you can try to further remove the variation by something like the following: 

```
pData(cds)$total_umi <- slam::col_sums(exprs(cds))
cds <- preprocessCDS(cds, residualModelFormulaStr = '~total_umi')
```

**Comment by ravipatel4** [comment]
Thanks Xiaojie for the quick reply.

I think it wans't clear from my message that my cells cluster based on nUMI when I cluster the cells outside Monocle (e.g., hierarchical clustering in R). I was doing this before running the data through the Monocle as a part of my QC pipeline to learn the nature of data before drawing any conclusions from the Monocle output.

It is a relief to know that Monocle also removes unwanted sources of variations. A follow-up question I have is, is there any way to extract the data after unwanted variation is removed by Monocle? The reason I ask this is, in addition to performing clustering and pseudo-time analysis using Monocle, I want to perform additional analysis on the expression data using standard R packages. And my analysis would be greatly helped if I can extract the expression data that already is devoid of unwanted variations.

Thank your for your help.

Best,
Ravi

**Comment by ravipatel4** [comment]
To add to my response above, I performed clustering using Monocle too. I have attached my code below. I see a nUMI-based clustering in Monocle too. Please look at the screen-shots of the plots. 
**The clustering of cells using Monocle:**
Code: `plot_cell_clusters(cds, color_by = 'as.factor(Cluster)')`
![clustering](https://user-images.githubusercontent.com/3804100/43805817-3eaf8d72-9a6f-11e8-97a1-4ebddfa3425c.png)
I can clearly see sub-clusters in cluster2. But nUMI seems to be masking any further clustering.



**The correlation of clusters and nUMI (x-axis represents clusters):**
Code: `plot(pData(cds)$Cluster, pData(cds)$nUMI, ylab="nUMI")`
![clustervsnumi](https://user-images.githubusercontent.com/3804100/43805894-787971e4-9a6f-11e8-8e1f-5bbf379abb36.png)

Please let me know if I am doing anything wrong. Or do you think this is just biological?

Thank you for your help.

Best,
Ravi

Here is the code I used to perform clustering in Monocle.
`cds = importCDS(seuratObj)`
`cds <- estimateSizeFactors(cds)`
`cds <- estimateDispersions(cds)`
`cds <- detectGenes(cds, min_expr = 0.1)`
`cds <- reduceDimension(cds, max_components = 2, norm_method = 'log', num_dim = 3, reduction_method = 'tSNE', verbose = T)`
`cds <- clusterCells(cds, verbose = F)`
`plot_cell_clusters(cds, color_by = 'as.factor(Cluster)')`

**Comment by Xiaojieqiu** [comment]
https://github.com/cole-trapnell-lab/monocle-release/issues/178#issuecomment-411217708
To extract the normalized and unwanted variation removed data, you need to mess around Monocle's source code a little bit. But basically, you can go to the debug model of the `reduceDimension` function (first run `debug(reduceDimension)` and then run `cds <- reduceDimension(cds, max_components = 2, norm_method = 'log', num_dim = 3, reduction_method = 'tSNE', verbose = T)` you have ) and save the `FM` matrix right before applying tSNE dimension reduction. Let me know if this makes sense to you. 

Also, please don't forgot to use `, residualModelFormulaStr = '~total_umi'` argument in your `reduceDimension` call

**Comment by ravipatel4** [comment]
@Xiaojieqiu, yes I could do exactly what you suggested and could obtain the data I was looking for. Thank you very much for your help! :) +1: 

As a reference to people who might be in the same situation as me, I think the reason I see nUMI-based clustering using monocle although monocle regresses out UMI counts is that there is a biological difference between those two populations, which leads to two distinct clusters. I reached to this conclusion by spending lot of time looking closely at the gene expression patters within each cluster and finding that cells in these two clusters are indeed different.
