### ISSUE TITLE
'rgl' not Available for Package 'monocle'

### ISSUE THREAD

**Issue by h1hui** [cole-trapnell-lab/monocle-release#203]
Hi all,

When I try to install the new release of monocle3, an error popped up saying that dependency 'rgl' is not available for package monocle. Does anyone know what to do?

Thanks,
Ashley

**Comment by MichaelPeibo** [comment]
Hi @h1hui 
Did you install it finally?
I got the same problem for installing 'rgl'

![image](https://user-images.githubusercontent.com/32219336/51734289-108c8e00-20bf-11e9-95c2-d48ef0f2cc01.png)

**Comment by macros29** [comment]
I am facing exactly the same issue. Can we somehow bypass the rgl dependency if not using 3D visualization?

**Comment by brianpenghe** [comment]
same here

**Comment by July233** [comment]
can solve this problem?
