### ISSUE TITLE
Is it possible to illustrate a "Seurat Alignment" dataset in the trajectory Plot with Monocle?

### ISSUE THREAD

**Issue by MichaelStreuber** [cole-trapnell-lab/monocle-release#204]
Hi all,

I loaded a Seurat Aligmment Dataset with two experimental groups (treated and untreated condition) into Monocle.

In Seurat you can nicely visualize the two aligned datasets (treated in blue and untreated in grey) directly in the t-SNE Plot like below:

![image](https://user-images.githubusercontent.com/34674278/45537246-0189fb00-b804-11e8-9707-1de4ed4ac7ad.png)

My question is:
Is there a way to visualize two experimental groups/Seurat Alignment datasets like treated and untreated in the trajectory plot like below (I made a draft with Power Point):

![image](https://user-images.githubusercontent.com/34674278/45537018-73157980-b803-11e8-925e-4d0b35ff9fca.png)

Best,
Michael

**Comment by MichaelStreuber** [comment]
Hello all ;)

Fortunately, I could solve the problem together with a colleague.

We used head() command to see the columns with identities and there I used the column name "treated":

(below you see all column names)
nGene | nUMI | orig.ident | percent.mito | S.Score | G2M.Score | Phase | old.ident | treated | res.1.4 | Size_Factor | CellType | num_genes_expressed | Pseudotime | State

Then I plot it with the command
plot_cell_trajectory(object_name, color_by = "treated")

![image](https://user-images.githubusercontent.com/34674278/46080152-6bf25200-c199-11e8-9aea-056be4029def.png)

Best,
Michael

**Comment by ZHANGHAO007** [comment]
I am having the same issue and am wondering what's the resolution to your problem. Any feedback would be appreciated!

**Comment by MichaelStreuber** [comment]
Hi ZHANGHAO007,

Sorry for getting back to you so late. 
Did you manage to plot your trajectory plot for different conditions with my recommendation from above?

Best,
Michael

**Comment by ZHANGHAO007** [comment]
>           Hi ZHANGHAO007,
> Sorry for getting back to you so late.
> Did you manage to plot your trajectory plot for different conditions with my recommendation from above?
> Best,
> Michael

thank you for your reply! I really want to plot a similar trajectory plot like yours. but I have failed. Can you tell me your script?
