### ISSUE TITLE
Error in estimateDispersions

### ISSUE THREAD

**Issue by spietrzak** [cole-trapnell-lab/monocle-release#208]
I am setting up a new CDS for some single cell data in Monocle, but I am getting the following error when I run estimateDispersions:
Error in rounded[nzGenes, ] : subscript out of bounds
I have used Monocle several times to analyze this type of single cell data before, but this is my first time encountering this error. I have done nothing differently when setting up my pheno data, feature data, counts table, etc., so I am not sure why I am seeing this now. Any ideas on what the issue is? Thanks.

**Comment by Payne-Wang** [comment]
I also met this question before. The data you input maybe the form of TPM/FPKM,I guess! When I converted  it to relative mRNA counts with the function called "relative2abs",the error appeared! I found there were lots of NaN in my dataset after convertion, but i don't know the reason！！！
