### ISSUE TITLE
Relative values after using relative2abs

### ISSUE THREAD

**Issue by csimona** [cole-trapnell-lab/monocle-release#21]
Hi,

**Later edit: Read the Census paper and saw that transcripts counts are also normalized and relative, so it all makes sense now (the name of the function `relative2abs` was the confusing part).**

**Original message:**
Thanks for developing and maintaining Monocle2, it's a great tool! My question is related to the type of data I should expect after using `relative2abs`. More specifically, I have a TPM dataset, which I read into a CellDataSet object like this

`HSMM <- newCellDataSet(matrix.rsem_filter, phenoData = pd, featureData = fd)`

A random sample from my object looks like that

```
exprs(HSMM)[1:5, 4]

 A1BG A1BG-AS1     A1CF      A2M  A2M-AS1 
 0.00     0.00     0.41   281.39     0.00 
```
I want to transform the data to absolute counts, so I do

`rpc_matrix <- relative2abs(HSMM)`

followed by 

```
HSMM <- newCellDataSet(as(as.matrix(rpc_matrix), "sparseMatrix"),
                       phenoData = pd,
                       featureData = fd,
                       lowerDetectionLimit=1,
                       expressionFamily=negbinomial.size())
```

My understanding is that I should now expect **absolute** count levels in my new `HSMM` object (or in `rpc_matrix`). Instead, the values I have are still relative:

```
rpc_matrix[1:5, 4]
A1BG    A1BG-AS1        A1CF         A2M     A2M-AS1 
0.000000000 0.000000000 0.003786963 2.599057193 0.000000000 
```
In this case, I am wondering whether setting `lowerDetectionLimit=1` is informative, since the data is still relative, and, for example, gene _A1CF_, which would have been above the limit before transformation, it's now below the limit.

Thanks!

Simona

**Comment by Xiaojieqiu** [comment]
Hi Simona, 

Thanks for this comment! Yes, the output got from relative2abs are not integer counts. Basically relative2abs converts TPM values to relative transcript counts based on a guess total mRNAs in each cell. We didn't round up the fraction part of the output values. But we used rounded up values when doing DEG test (including BEAM).
