### ISSUE TITLE
Column gene_short_name in fData required for many functions

### ISSUE THREAD

**Issue by timoast** [cole-trapnell-lab/monocle-release#22]
Hi,

I spent a little time today trying to work out why setting the `markers` argument in `plot_cell_trajectory` wasn't doing anything, before I realised it's actually required that a column in the `fData` is named `gene_short_name` (I had named it just `gene_name`).

This wasn't stated in the vignette when describing how to construct the `CellDataSet` object and it's not really in the manual as far as I can tell. I think it would be useful to have this more explicitly stated somewhere (like in the vignette). 

Cheers,
Tim

**Comment by Xiaojieqiu** [comment]
Hi Tim,

Thanks for your comments. We will state this requirement in the vignette in our next release

**Comment by ctrapnell** [comment]
@Xiaojieqiu, we should probably also add some code in newCellDataSet() that looks for gene_short_name in the columns of the fData table and emits a warning if its missing.

**Comment by andysheh** [comment]
Hey Tim, 

Thank you for bringing this issue to light, it is much appreciated. I've included a statement in the next release's vignette that addresses this and I've included code that will trigger warnings if the fData does not have a column named gene_short_name.
