### ISSUE TITLE
Visualize phenotypically colored cells on top layer

### ISSUE THREAD

**Issue by skurp** [cole-trapnell-lab/monocle-release#228]
I am curious if there is a simple solution to layering phenotypically colored cells on top of background cells. For example, using `plot_cell_trajectory(HSMM, color_by = "low_freq_cell_type")` some of the colored cells are obscured by the cells that are not this cell type. I would like them to be prioritized visually, and plotted on the top layer of the trajectory.

**Comment by skurp** [comment]
You can arrange the column you want to `color_by` in `pData(HSMM)` for order of plotting (first values in vector plotted first, last plotted last, i.e. on top). You then need to rearrange the columns in HSMM@reducedDimS to match this order.

**Comment by KathiRin** [comment]
@wconnell Could you please explan how you rearranged the columns in HSMM@reducedDimS according to the order of the desired column in pData?
