### ISSUE TITLE
10x data  

### ISSUE THREAD

**Issue by enhaofrank** [cole-trapnell-lab/monocle-release#24]
hi, 
i used the 10x data to run this code:
cellranger_pipestance_path <- "/path/to/your/pipeline/output/directory"
gbm <- load_cellranger_matrix(cellranger_pipestance_path)
gbm_cds <- newCellDataSet(exprs(gbm),
phenoData = pData(gbm),
featureData = fData(gbm),
lowerDetectionLimit=0.5,
expressionFamily=negbinomial.size())

but, the error happened:
Error: CellDataSet 'phenoData' is class 'data.frame' but should be or extend 'AnnotatedDataFrame'

Any reply will be appreciated. 
Thanks 
frank

**Comment by Xiaojieqiu** [comment]
Hi Frank, 

Thanks for running Monocle 2 on 10x (which we do a lot here in our lab). The error is actually self-explanatory. the input to phenoData/featureData should be `AnnotatedDataFrame` instead of `data.frame`. please replace the 
 `pData(gbm)` and  ` fData(gbm` as  `new("AnnotatedDataFrame",` data =pData(gbm))` and
` new("AnnotatedDataFrame", data = fData(gbm))`. I believe this is a mistake we made in our recent release vignette. We will fix this in our next release. 

Thanks and hope this helps.

**Comment by nbahlis** [comment]
Hi 
I am getting the following error as well
Warning message:
In newCellDataSet(exprs(gbm), phenoData = new("AnnotatedDataFrame",  :
  None of your featureData columns are named 'gene_short_name', some functions will not be able
           to take this function as input as a result

Any advice, thanks you

**Comment by rmtsoa** [comment]
I got same error messages. The following is what I did to fix it:

colnames(fData(gbm)) <- c('id', 'gene_short_name')
Monocle.gbm <- newCellDataSet(exprs(gbm), 
                                    phenoData = new('AnnotatedDataFrame', data = pData(gbm)),
                                    featureData = new('AnnotatedDataFrame', fData(gbm)),
                                    lowerDetectionLimit = 0.5,
                                    expressionFamily = negbinomial.size())

You should get the dgCmatrix.
Rosemarie

**Comment by Xiaojieqiu** [comment]
thanks Rosemarie. we need a gene_short_name column in the fData. Some of our functions (especially plotting functions) relies on this column. We will update our vignette to better introduce how to create a cds from 10x dataset

**Comment by mheskett** [comment]
I got this error message

_Warning message:
In newCellDataSet(exprs(gbm), phenoData = new("AnnotatedDataFrame",  :
  None of your featureData columns are named 'gene_short_name', some functions will not be able
           to take this function as input as a result_

Seems like this is an easy fix that is preventing 10X users from loading data into Monocle correctly. We would greatly benefit from this being fixed.

**Comment by verma014** [comment]
You can run the following script in the meantime. 
------------
library(cellrangerRkit)
library(monocle)

#Cell cells from cell ranger R Kit
cellranger_pipestance_path_1 <- paste0(getwd(),"/AllCells") 
AllCells <- load_cellranger_matrix(cellranger_pipestance_path_1)
#Split the cell ranger files
AllCells_exprs<-exprs(AllCells)
AllCells_pd<-pData(AllCells)
AllCells_fd<-fData(AllCells)
#Modify the gene title to gene_short_name which is required by monocle
colnames(AllCells_fd)[2]<-"gene_short_name"
AllCells_fd<-new("AnnotatedDataFrame",data = AllCells_fd)
# Now start the Monocle script

AllCells<-newCellDataSet(cellData = as.matrix(AllCells_exprs),
                         phenoData=AllCells_pd,
                         featureData = AllCells_fd,
                         expressionFamily = negbinomial(),
                         lowerDetectionLimit = .5)

**Comment by Xiaojieqiu** [comment]
@andysheh could you please update the monocle 2 website for this?

**Comment by Sophia409** [comment]
@enhaofrank @Xiaojieqiu @nbahlis 
Why I can't find a ID column in my data and cds fvarLabels.?plot_genes_in_pseudotime functions relies on this column, but I can't find "id" .
```
> my_pseudotime_de %>% arrange(qval) %>% head()
  status           family pval qval gene_short_name num_cells_expressed use_for_ordering
1     OK negbinomial.size    0    0        Serpine2                2330             TRUE
2     OK negbinomial.size    0    0           Ramp1                1623             TRUE
3     OK negbinomial.size    0    0             Dbi                5190             TRUE
4     OK negbinomial.size    0    0          Pea15a                3707             TRUE
5     OK negbinomial.size    0    0          Atp1a2                1789             TRUE
6     OK negbinomial.size    0    0            Gatm                1587             TRUE
> tdcds
CellDataSet (storageMode: environment)
assayData: 54233 features, 5621 samples 
  element names: exprs 
protocolData: none
phenoData
  sampleNames: AAACCTGAGCAGCGTA AAACGGGCAGCTCGCA ... TGCTACCGTCGGCACT (5621 total)
  varLabels: orig.ident nCount_RNA ... State (15 total)
  varMetadata: labelDescription
featureData
  featureNames: 4933401J01Rik Gm26206 ... tdTomato (54233 total)
  fvarLabels: gene_short_name num_cells_expressed use_for_ordering
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'
Annotation:  
```
I follow [this turtorial ](https://davetang.org/muse/2017/10/01/getting-started-monocle/)to do monocle analysis,in his picture,he selected the top 6 genes using "id", and there is a" id "among fvarLabels in his featureData,like this:
![default](https://user-images.githubusercontent.com/30619010/53402281-68832100-39ec-11e9-80d2-c0474a62c941.png)
![default](https://user-images.githubusercontent.com/30619010/53405809-9cae1000-39f3-11e9-860e-eba6a49829e1.png)
Can you help me?

**Comment by Sophia409** [comment]
@Xiaojieqiu
