### ISSUE TITLE
how to extract branch expr matrix from plot_pseudotime_heatmap to calculate Foldchange

### ISSUE THREAD

**Issue by Flyingcattle** [cole-trapnell-lab/monocle-release#241]
Hi, I want to compare gene expression between two branches using volcano map, I have extracted expression matrix using "plot_genes_branched_heatmap", but I just donot know how to calculate log2FC and extract pValue here, thanks for your help !
branch_genes <- plot_genes_branched_heatmap(x,  return_heatmap = T)
write.csv(branch_genes$BranchA_exprs, file="BranchA_exprs_matrix.csv")

**Comment by WangLab401** [comment]
Hi, could you share your experience about this part? I want to calculate the p-value of BranchA vs BranchB_exprs_matrix,  is any R package  available? As I know, the popular package of DESeq2 is based on the reads count, is it be available here?
