### ISSUE TITLE
Vignette not up to date

### ISSUE THREAD

**Issue by nachocab** [cole-trapnell-lab/monocle-release#25]
I think the monocle 2 vignette has not been entirely updated. There are references to several functions that are not longer present. For example: plot_pc_variance_explained or plot_cell_clusters

**Comment by Xiaojieqiu** [comment]
Hi Nachocab, 

Are you sure you are using the newest Monocle 2 version from bioconductor? Those functions (`plot_pc_variance_explained` or `plot_cell_clusters`) are recently added into the package and they should be there. (see the documented functions in Monocle 2: https://bioconductor.org/packages/release/bioc/manuals/monocle/man/monocle.pdf)

**Comment by cnshulse** [comment]
Hi,
I am having the exact same issue. I installed monocle as follows:

source("https://bioconductor.org/biocLite.R")
biocLite("monocle")

In R Studio, it says I have monocle version 2.2.0, however I am not able to use plot_pc_variance_explained or plot_cell_clusters. How can I fix this?

Thanks!
Christine

**Comment by skupe** [comment]
Hi,

also same issue here ... and also tsne is not an option for reduceDimension() in the current bioconducter version 2.2.0. 

maybe the version on bioconducter has to be updated? or where to find a version in accordance with the vignette?

thanks,
alex

**Comment by Xiaojieqiu** [comment]
Hi I think using biocLite may not make you to get monocle 2.4.0? 

You can see that the current version of monocle is 2.4.0 (not 2.2.0): 
https://bioconductor.org/packages/release/bioc/html/monocle.html

Please try to download the package from the above link and install it locally

**Comment by cnshulse** [comment]
Okay thanks I see I am running 2.4.0 now, installing locally fixed it for me.

**Comment by skupe** [comment]
yep - same for me: with monocle 2.4.0 everything works fine. thanks and greetings to Seattle!

**Comment by maspil** [comment]
Hi, 
Trying to install the newest version of monocle (2.8?). Following your link and installing from bioconductor release 3.8, I get version 2.10.1 of monocle. Should this version be updated on bioconductor?
