### ISSUE TITLE
Trouble loading CellRanger 3.0 10x Data

### ISSUE THREAD

**Issue by tmccra2** [cole-trapnell-lab/monocle-release#254]
Hello!

I can't load the Cell Ranger 3.0 10x data into monocle because the command importCDS() gives the error: 
Error in importCDS(mat) : the object type you want to export to is not supported yet

I tried to follow the vignette shown here: https://github.com/cole-trapnell-lab/monocle-release/commit/fe7599c678061e1ed99a69851f6c99df0595b51a?diff=unified

But got the error: 

Error in get_matrix_dir_path(pipestance_path, barcode_filtered) : 
  Could not find matrix folder: ~/Downloads/Org/outs/filtered_gene_bc_matrices_mex

It seems to be looking for a _mex file, while I only have these files 
![screen shot 2019-01-22 at 4 31 37 pm](https://user-images.githubusercontent.com/46829204/51573265-37a05100-1e6e-11e9-812f-cc7986a44362.png)

I'm just having a heck of a time loading my data in here :/ 
Thanks for any help!

**Comment by xizhihui** [comment]
hi,
I think you should change features.tsv to genes.tsv, maybe this will help, I don't remember very well.

**Comment by Xiaojieqiu** [comment]
Did you delete the *filtered_**gene_bc_matrices_mex* file in your folder
somehow? cellranger should always give you that file by default

**Comment by tmccra2** [comment]
A sequencing core ran the Cell Ranger pipeline for us and that was the file they sent to us. I'll check with them really quickly to see if they can send me that file type

**Comment by evolvedmicrobe** [comment]
CellRanger 3.0 no longer produces a `filtered_gene_*` files or folders, as the output format has changed.

You appear to be using the older (pre-3.0) method to load CellRanger data, while the new method is required.  In particular, the function `get_matrix_dir_path` is likely being called from within the now deprecated rkit package.  Instead, try loading the data using the new functions included in Monocle, in particular the function `load_cellranger_data` (not the older `load_cellranger_matrix`). 

If you're unable to get this to work, please upload the results of the `sessionInfo()` command, as it's possible you do not have the latest version of Monocle.

**Comment by tmccra2** [comment]
That worked! Thanks!

**Comment by tmccra2** [comment]
Upon updated to try the new monocle I am having problems again: http://cole-trapnell-lab.github.io/monocle-release/monocle3/

I run the code from the vignette: [fe7599c?diff=unified](https://github.com/cole-trapnell-lab/monocle-release/commit/fe7599c678061e1ed99a69851f6c99df0595b51a?diff=unified)

I load the data: > org1 <- load_cellranger_data(cellranger_pipestance_path)

And get the following error: Error in negbinomial.size() : could not find function "negbinomial.size"

**Comment by AnaHowellsFerreira** [comment]
Hi!
I am having issues with loading 10x data. I have ran a whole analysis with Seurat3 of this data, so I know that the data is there and in the right format for Seurat, but was wondering if there's anything I am missing regarding the 10x data and format to be loaded into Monocle3. Do I need anything else besides features, barcode and matrix output?

Thank you!

> sessionInfo("monocle3")
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
character(0)

other attached packages:
[1] monocle3_0.1.0

I keep getting the following error:

> cds <- load_cellranger_data("/Users/anaferreira/Desktop/190501_A00561_0026_BH7TTGDRXX/")
Error in load_cellranger_data("/Users/anaferreira/Desktop/190501_A00561_0026_BH7TTGDRXX/") : 
  Could not find the pipestance output directory: '/Users/anaferreira/Desktop/190501_A00561_0026_BH7TTGDRXX//outs'. Please double-check if the directory exists.

**Comment by scideas** [comment]
> Hi!
> I am having issues with loading 10x data. I have ran a whole analysis with Seurat3 of this data, so I know that the data is there and in the right format for Seurat, but was wondering if there's anything I am missing regarding the 10x data and format to be loaded into Monocle3. Do I need anything else besides features, barcode and matrix output?

I've tried arranging the files as they'd appear as raw cell ranger output folders with the hope it would be able to read the above files, but no such luck...
> 
> Thank you!
> 
> > sessionInfo("monocle3")
> > R version 3.5.1 (2018-07-02)
> > Platform: x86_64-apple-darwin15.6.0 (64-bit)
> > Running under: macOS  10.14.5
> 
> Matrix products: default
> BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> character(0)
> 
> other attached packages:
> [1] monocle3_0.1.0
> 
> I keep getting the following error:
> 
> > cds <- load_cellranger_data("/Users/anaferreira/Desktop/190501_A00561_0026_BH7TTGDRXX/")
> > Error in load_cellranger_data("/Users/anaferreira/Desktop/190501_A00561_0026_BH7TTGDRXX/") :
> > Could not find the pipestance output directory: '/Users/anaferreira/Desktop/190501_A00561_0026_BH7TTGDRXX//outs'. Please double-check if the directory exists.

I'm having the same issue as AnaHowells-Ferreira. I have all 3 files that are required for building the matrix successfully in Seurat, including barcodes.tsv, features.tsv, & matrix.mtx. 
Any word on what the problem was?

**Comment by kmshort** [comment]
> > > Could not find the pipestance output directory: '/Users/anaferreira/Desktop/190501_A00561_0026_BH7TTGDRXX//outs'. Please double-check if the directory exists.
> 
> I'm having the same issue as AnaHowells-Ferreira. I have all 3 files that are required for building the matrix successfully in Seurat, including barcodes.tsv, features.tsv, & matrix.mtx.
> Any word on what the problem was?

I had this same problem. I find that Monocle's implementation for loading CellRanger data is poor.
It requires hard-wired directory structures for it to work. As you can see from the first post, you MUST have a directory structure like:
experimentX > outs > filtered_feature_bc_matrix > files
I just had "files" in a directory which had a completely different name; something like.
cds1 <- load_cellranger_data("~/experimentX/cellrangerData/") (with .gz barcodes, features and matrix files in the cellrangerData directory). You'll notice my second issue there... 

THEN, all my files were .gz, not uncompressed. load_cellranger_data couldn't deal with gzipped files.

So, it only worked when I (a) move the files into a set directory structure, AND provided the uncompressed TSV and mtx files, like:
my directory format:
experimentX > outs > filtered_feature_bc_matrix > files (TSV/mtx format, not gz)

function:
cds1 <- load_cellranger_data("~/experimentX")

I hope this helps someone else - because it was as clear as mud for me, and the help documentation wasn't useful if you're not aware of the structure of ("the output directory produced by Cell Ranger" - Monocle3 documentation).
Seurat does this the simple way, you give it the actual directory where the files are, and it handles .gz. Easy.

**Comment by Shanfeng439** [comment]
> > > > Could not find the pipestance output directory: '/Users/anaferreira/Desktop/190501_A00561_0026_BH7TTGDRXX//outs'. Please double-check if the directory exists.
> > 
> > 
> > I'm having the same issue as AnaHowells-Ferreira. I have all 3 files that are required for building the matrix successfully in Seurat, including barcodes.tsv, features.tsv, & matrix.mtx.
> > Any word on what the problem was?
> 
> I had this same problem. I find that Monocle's implementation for loading CellRanger data is poor.
> It requires hard-wired directory structures for it to work. As you can see from the first post, you MUST have a directory structure like:
> experimentX > outs > filtered_feature_bc_matrix > files
> I just had "files" in a directory which had a completely different name; something like.
> cds1 <- load_cellranger_data("~/experimentX/cellrangerData/") (with .gz barcodes, features and matrix files in the cellrangerData directory). You'll notice my second issue there...
> 
> THEN, all my files were .gz, not uncompressed. load_cellranger_data couldn't deal with gzipped files.
> 
> So, it only worked when I (a) move the files into a set directory structure, AND provided the uncompressed TSV and mtx files, like:
> my directory format:
> experimentX > outs > filtered_feature_bc_matrix > files (TSV/mtx format, not gz)
> 
> function:
> cds1 <- load_cellranger_data("~/experimentX")
> 
> I hope this helps someone else - because it was as clear as mud for me, and the help documentation wasn't useful if you're not aware of the structure of ("the output directory produced by Cell Ranger" - Monocle3 documentation).
> Seurat does this the simple way, you give it the actual directory where the files are, and it handles .gz. Easy.

Thanks for your method!
My fianl solution was similar to you, but it only worked with .gz files.

**Comment by aw2211** [comment]
Hello, your solution has worked to find the correct directory, but then I have an additional problem:
Error in get_genome_in_matrix_path(matrix_dir, genome) : 
  Multiple genomes found; please specify one. 
 Genomes present: barcodes.tsv.gz, features.tsv.gz, matrix.mtx.gz

what am I supposed to do now?

Thank you!
Anna
