### ISSUE TITLE
Seurat object can't be imported into monocle:the object type you want to export to is not supported yet

### ISSUE THREAD

**Issue by Sophia409** [cole-trapnell-lab/monocle-release#262]
Hello,
@ctrapnell @rcannood @evolvedmicrobe 
 I was wondering  why my Seurat object can't be imported into monocle? I follow the official website to do it, but it turns out that the importCDS doesn't take that.
 Below is the R code and my sessioninfo.If you do know of how to might help us, that would be incredibly helpful!
Thank you!
Sophia
`> library(monocle)
> mo <- importCDS(tc, import_all = TRUE)
Error in importCDS(tc, import_all = TRUE) : 
  the object type you want to export to is not supported yet
> mo <- importCDS(tc)
Error in importCDS(tc) : 
  the object type you want to export to is not supported yet
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936    LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                               LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
 [1] splines   stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] Seurat_3.0.0.9000    monocle_2.8.0        DDRTree_0.1.5        irlba_2.3.3          VGAM_1.1-1           ggplot2_3.1.0        Biobase_2.40.0      
 [8] BiocGenerics_0.26.0  BiocInstaller_1.30.0 Matrix_1.2-15       

loaded via a namespace (and not attached):
  [1] Rtsne_0.15             colorspace_1.4-0       ggridges_0.5.1         rprojroot_1.3-2        fs_1.2.6               rstudioapi_0.9.0      
  [7] listenv_0.7.0          npsurv_0.4-0           remotes_2.0.2          ggrepel_0.8.0          codetools_0.2-16       R.methodsS3_1.7.1     
 [13] docopt_0.6.1           lsei_1.2-0             pkgload_1.0.2          jsonlite_1.6           ica_1.0-2              cluster_2.0.7-1       
 [19] png_0.1-7              R.oo_1.22.0            pheatmap_1.0.12        httr_1.4.0             compiler_3.5.2         backports_1.1.3       
 [25] assertthat_0.2.0       lazyeval_0.2.1         limma_3.36.5           cli_1.0.1              htmltools_0.3.6        prettyunits_1.0.2     
 [31] tools_3.5.2            rsvd_1.0.0             igraph_1.2.4           gtable_0.2.0           glue_1.3.0             RANN_2.6.1            
 [37] reshape2_1.4.3         dplyr_0.8.0.1          Rcpp_1.0.0             slam_0.1-44            gdata_2.18.0           ape_5.2               
 [43] nlme_3.1-137           gbRd_0.4-11            lmtest_0.9-36          stringr_1.4.0          globals_0.12.4         ps_1.3.0              
 [49] testthat_2.0.1         gtools_3.8.1           devtools_2.0.1         future_1.11.1.1        MASS_7.3-51.1          zoo_1.8-4             
 [55] scales_1.0.0           RColorBrewer_1.1-2     yaml_2.2.0             reticulate_1.10        memoise_1.1.0          pbapply_1.4-0         
 [61] gridExtra_2.3          fastICA_1.2-1          stringi_1.3.1          desc_1.2.0             caTools_1.17.1.1       densityClust_0.3      
 [67] pkgbuild_1.0.2         bibtex_0.4.2           Rdpack_0.10-1          SDMTools_1.1-221       rlang_0.3.1            pkgconfig_2.0.2       
 [73] matrixStats_0.54.0     bitops_1.0-6           qlcMatrix_0.9.7        lattice_0.20-38        ROCR_1.0-7             purrr_0.3.0           
 [79] htmlwidgets_1.3        cowplot_0.9.4          processx_3.2.1         tidyselect_0.2.5       plyr_1.8.4             magrittr_1.5          
 [85] R6_2.4.0               gplots_3.0.1.1         combinat_0.0-8         pillar_1.3.1           withr_2.1.2            fitdistrplus_1.0-14   
 [91] survival_2.43-3        tsne_0.1-3             tibble_2.0.1           future.apply_1.1.0     crayon_1.3.4           KernSmooth_2.23-15    
 [97] plotly_4.8.0           viridis_0.5.1          usethis_1.4.0          grid_3.5.2             data.table_1.12.0      FNN_1.1.3             
[103] callr_3.1.1            HSMMSingleCell_0.114.0 metap_1.1              sparsesvd_0.1-4        digest_0.6.18          tidyr_0.8.2           
[109] R.utils_2.8.0          munsell_0.5.0          viridisLite_0.3.0      sessioninfo_1.1.1     `
![image](https://user-images.githubusercontent.com/30619010/53000773-111d0800-3464-11e9-9d42-a5278318523f.png)

**Comment by ncalistri** [comment]
Give this a shot, replacing 'seurat_object' with your seurat object's name. You can skip the RDS loading if you already have the seurat object in memory: 

```
#Load Seurat object
seurat_object <- readRDS('seurat_object.rds')

#Extract data, phenotype data, and feature data from the SeuratObject
data <- as(as.matrix(seurat_object@assays$RNA@data), 'sparseMatrix')

pd <- new('AnnotatedDataFrame', data = seurat_object@meta.data)

fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
fd <- new('AnnotatedDataFrame', data = fData)

#Construct monocle cds
monocle_cds <- newCellDataSet(data,
                         phenoData = pd,
                         featureData = fd,
                         lowerDetectionLimit = 0.5,
                         expressionFamily = negbinomial.size())
```

Seurat changed the way their objects are structured with the 3.0 pre-release, so the built-in function says it's no longer compatible. You can still manually extract the data, phenotype data, and feature data from the seurat object, and build the monocle CDS though.

You can inspect the 'importCDS' function by typing just the function name without any parenthesis, and you'll see that the code I supplied you is almost identical to what the 'importCDS' function does behind the scenes, just without any of the error or compatibility checking.

**Comment by Sophia409** [comment]
@ncalistri Hello, thank you very much for your help to me.ButI I encounterred into a question when i want to view the monocle_cds data by using this code.Below is the error:
` View(monocle_cds)
Error in if (more || nchar(output) > 80) { : 
  missing value where TRUE/FALSE needed`
![default](https://user-images.githubusercontent.com/30619010/53154605-288bfa80-35f6-11e9-86ed-7a291127199f.png)
![default](https://user-images.githubusercontent.com/30619010/53154722-5ec97a00-35f6-11e9-8699-a72fc7c4de17.png)
What should I do?Can you give me some advice?Thank you！

**Comment by ncalistri** [comment]
It's very probably that the code worked, however the 'view()' function doesn't work nicely with an entire annotated data frame.

You can read more about annotated data frames here: https://www.rdocumentation.org/packages/Biobase/versions/2.32.0/topics/AnnotatedDataFrame

And if you want to view the data frame, you simply nest the 'fData()' or 'pData()' commands around your monocle_cds like this:

```
view(pData(monocle_cds))
view(fData(monocle_cds))
```

**Comment by Sophia409** [comment]
@ncalistri You solved my problem,Thank you so much !

**Comment by Sophia409** [comment]
@ncalistri  Hello, I have another question to consult youu. I need to merge my seurat data of 3 experimental time points with the Hippocampus data provided by Guided Clustering of the Mouse Cell Atlas: loom edition. I merged my own data by using the merge command and do trajectory analysis using monocle. But I don't know how to convert this loom file to seurat object or expression matrix, so that I can merge them with my data and do next analysis.
The tutorial says that : Seurat offers a conversion function to go from Seurat objects to loom files. The reverse conversion is currently in progress.
Does it means that I could't convert loom file to seurat? So what should I do to merge them? Can you give me some advice?Thank you very much!
![default](https://user-images.githubusercontent.com/30619010/53714120-352b1100-3e88-11e9-94fc-34a7262027e4.png)

**Comment by kgerner** [comment]
Hi Everyone, 

I have been trying to import my Seurat object into Monocle, but have had no luck. I tried the method above, but my Assay Data slot is empty. Is this a slot that needs to be manually filled? If so, how can you fill that slot? I would like to be able to move from Seurat to Monocle.

Thank you,
Kamryn

**Comment by nvanspyk** [comment]
> I have been trying to import my Seurat object into Monocle, but have had no luck. I tried the method above, but my Assay Data slot is empty. Is this a slot that needs to be manually filled? If so, how can you fill that slot? I would like to be able to move from Seurat to Monocle.

@kgerner Did you figure out the "Assay Data slot is empty" issue? If so, please share :)

**Comment by Dragonmasterx87** [comment]
@ncalistri you deserve a cookie!! What an excellent yet simple piece of code!!

**Comment by Dragonmasterx87** [comment]
@kgerner @nvanspyk What's the issue exactly, does your Seurat object not transform into the monocle data frame for ordering? Explain how you have normalized and thresholded your Seurat object, and I can tell you how to perform your ordering analysis.

**Comment by kgerner** [comment]
@Dragonmasterx87 I finally figured out how to pass a Seurat object into monocle without filling the assay data slot (I've only done it once) but I am unable to make a heatmap. The 'ID" column is missing from the monocle object which is how I've been ordering the qvalues for heatmap generation.

**Comment by Dragonmasterx87** [comment]
@kgerner Ok I'm not sure if I understand your current situation.. So if you are talking about generating heatmaps based on the pseudotemporal plots, then maybe I can help. If you want to make heatmaps of DE gene expression, use Seurat, its the best. Use monocle only for pseudotemporal gene expression analysis. Let me show you what I'm doing:

```
seuratX <- analysis.file

#Extract data, phenotype data, and feature data from the SeuratObject
data <- as(as.matrix(seuratX@assays$RNA@data), 'sparseMatrix')

pd <- new('AnnotatedDataFrame', data = seuratX@meta.data)

fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
fd <- new('AnnotatedDataFrame', data = fData)

#Construct monocle cds
HSMM <- newCellDataSet(data,
                              phenoData = pd,
                              featureData = fd,
                              #lowerDetectionLimit = 0.5,
                              expressionFamily = uninormal())# since I have already normalized, thresholded and scalled in Suerat v3.0.0.9150

#View data
pData(HSMM)
fData(HSMM)


#Run ordering algorithm
var_genes <- seuratX[["RNA"]]@var.features
ordering_genes <- var_genes

HSMM <- setOrderingFilter(HSMM, ordering_genes)
print(dim(exprs(HSMM)))

## reduce dimension - do not normalize or include pseudo count. Use monocle scaling
HSMM <- reduceDimension(HSMM,norm_method="none", 
                        reduction_method="DDRTree",
                        max_components=4,
                        scaling=TRUE,
                        verbose=TRUE,
                        pseudo_expr=0)

# First decide what you want to color your cells by
print(head(pData(HSMM)))

## order cells change colors and theta to match your plot
HSMM <- orderCells(HSMM)
plot_cell_trajectory(HSMM, 
                     color_by = "seurat_clusters",
                     theta = -15,
                     show_branch_points = FALSE,
                     show_tree = TRUE,
                     cell_size = 4) + scale_color_manual(breaks = c("X", "Y", "Z"), 
                                                         values=c("red",
                                                                        "green",
                                                                        "blue")) + theme(legend.position = "right")

# now onwards to pseudotemporal plots
genex <- c("geneX", "geneY")

sig_gene_names <- (genex)
head(sig_gene_names)
pseudotemporalplot <- plot_pseudotime_heatmap(HSMM[sig_gene_names],
                        num_clusters = 9, 
                        cores = 4,
                        hmcols = NULL,
                        show_rownames = T)

pseudotemporalplot
```


Hope that Helps!!!

**Comment by Lei-GitHub** [comment]
Hi, Thank you for the information. I followed this code to load my seurat Rds to monocle. I got the error that 
monocle_cds <- newCellDataSet(data,
+                               phenoData = pd,
+                               featureData = fd,
+                               lowerDetectionLimit = 0.5,
+                               expressionFamily = negbinomial.size())
Error in negbinomial.size() : could not find function "negbinomial.size"

<img width="796" alt="Screen Shot 2019-05-07 at 11 49 40 AM" src="https://user-images.githubusercontent.com/26446235/57313742-382bc300-70be-11e9-929a-db2db36c4daf.png">

Would you please suggest me how to figure it out? Thank you very much.

> ```
> #Load Seurat object
> seurat_object <- readRDS('seurat_object.rds')
> 
> #Extract data, phenotype data, and feature data from the SeuratObject
> data <- as(as.matrix(seurat_object@assays$RNA@data), 'sparseMatrix')
> 
> pd <- new('AnnotatedDataFrame', data = seurat_object@meta.data)
> 
> fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
> fd <- new('AnnotatedDataFrame', data = fData)
> 
> #Construct monocle cds
> monocle_cds <- newCellDataSet(data,
>                          phenoData = pd,
>                          featureData = fd,
>                          lowerDetectionLimit = 0.5,
>                          expressionFamily = negbinomial.size())
> ```

**Comment by ncalistri** [comment]
The 'negbinomial.size()' function is part of the package 'VGAM' so you should make sure it is installed, up to date, and loaded in your session.

```
install.packages('VGAM')

library(VGAM)

```

**Comment by Lei-GitHub** [comment]
Thank you very much @ncalistri.  Thanks.

**Comment by sluff-zz** [comment]
@ncalistri thank you! I had a script that worked last year but suddenly crapped out.

**Comment by Sophia409** [comment]
@ncalistri Hello, I solved the problem by you code in the past.But recently, monocle 3 has upgraded.And after I modify the code you gave me according to new new_cell_data_set function,it gave errors.Can you give me some help?Thank you very much.
`data <- Merge.integrated@assays$RNA@data
data <- GetAssayData(Merge.integrated,slot = "data")
cell_metadata <- new('AnnotatedDataFrame', data = Merge.integrated@meta.data)
fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
gene_metadata <- new('AnnotatedDataFrame', data = fData)
#Construct monocle cds
tdcds <-  new_cell_data_set(data,
cell_metadata = cell_metadata,
gene_metadata = gene_metadata
)`

`Error in as.data.frame.default(from) : 
  cannot coerce class ‘structure("AnnotatedDataFrame", package = "Biobase")’ to a data.frame`

**Comment by Sophia409** [comment]
@Dragonmasterx87 I follow your code,but it has an error.Can you help me analysis it ?
> tdmerge <- setOrderingFilter(tdmerge, ordering_genes)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘fData’ for signature ‘"Seurat"’

**Comment by naixiangxiaozi** [comment]
> @Dragonmasterx87 I finally figured out how to pass a Seurat object into monocle without filling the assay data slot (I've only done it once) but I am unable to make a heatmap. The 'ID" column is missing from the monocle object which is how I've been ordering the qvalues for heatmap generation.



> @Dragonmasterx87 I finally figured out how to pass a Seurat object into monocle without filling the assay data slot (I've only done it once) but I am unable to make a heatmap. The 'ID" column is missing from the monocle object which is how I've been ordering the qvalues for heatmap generation.
@kgerner 


> @kgerner @nvanspyk What's the issue exactly, does your Seurat object not transform into the monocle data frame for ordering? Explain how you have normalized and thresholded your Seurat object, and I can tell you how to perform your ordering analysis.

@Dragonmasterx87 Hi, I have got the same problem as they do. It show the error as shown in the screenshot blow:
![image](https://user-images.githubusercontent.com/42306818/64931998-9cdff280-d801-11e9-8536-3bd51eb58109.png)
Can you please help me solve this problem? Much appreciated!

**Comment by Dragonmasterx87** [comment]
Okay guys I'm looking into this give me a minute.

**Comment by Dragonmasterx87** [comment]
Alright, guys, it seems, like your RNA data isn't stored in your assay slot. here is my Seurat object metadata tree, can you show me your tree? 
Here is an example:

![image](https://user-images.githubusercontent.com/39837140/64968311-ef57f800-d86f-11e9-94fd-829f0fe5b225.png)

The data loaded into monocle from the Seurat object is in the Assay>RNA>data slot. You need to create a Seurat object for this assay slot to be generated.

A simple workaround, would be to use the following code instead:

`data <- as(as.matrix(seurat_object[["RNA"]]@data), 'sparseMatrix')`

Double parenthesis in R [[]] allows you to directly access a column or in this case, Seurat object metadata (based on my understanding). So this essentially bypasses the need to be 'exact' in your direction while pointing to metadata. 

🐲

**Comment by Dragonmasterx87** [comment]
Also, this is performed using Seurat v3.0.0, and monocle v2.8.0, there are issues in the v3 > v3 conversion which is still being sorted out, see issue [#1658](https://github.com/satijalab/seurat/issues/1658).

Also, on [reading the passage just above here](http://cole-trapnell-lab.github.io/monocle-release/docs/#importing-exporting-data-with-other-packages) it appears that non-normalized data should be used in monocle, I personally haven't seen much difference in the inference one gets from the two, but if that's the case, then use this: 

`data <- as(as.matrix(seurat_object[["RNA"]]@counts), 'sparseMatrix')`

Just something to keep in mind, it may affect how your graph looks or may not, I personally haven't seen any striking differences.

🐲

**Comment by naixiangxiaozi** [comment]
Hi,
Sorry for the late response. [cid:35a060ea-edfc-4570-bece-2b6eb2b209bc]
________________________________

**Comment by ncalistri** [comment]
With the finalized Seurat V3, it is recommended to use the GetAssayData() function to pull out count/expression matrices. I'd recommend using this function to ensure forward compatibility with any future Seurat updates that change how Seurat Objects are structured.

https://satijalab.org/seurat/essential_commands.html

**Comment by naixiangxiaozi** [comment]
I'm still using the Seurat version 2.3.4
________________________________

**Comment by Dragonmasterx87** [comment]
@naixiangxiaozi as @ncalistri says use the following:

`# Retrieve or set data in an expression matrix ('counts', 'data', and 'scale.data')
GetAssayData(object = pbmc, slot = "counts")
pbmc <- SetAssayData(object = pbmc, slot = "scale.data", new.data = new.data)`

Read the data access tab in the link ncalistri has provided.

**Comment by naixiangxiaozi** [comment]
It showed the error: "

Error in GetAssayData(cluster, slot = "counts") :
  object 'to.return' not found"

________________________________

**Comment by Dragonmasterx87** [comment]
Okay, so you are telling GetAssayData that the name of the suerat object is 'to.return' 😢 

Lets say the name of your seurat object is: shox2crepos_mtmg (based on your earlier post)

This is what you would have to do:
1. For Seurat normalized data:
`data <- as(as.matrix(shox2crepos_mtmg[["RNA"]]@data), 'sparseMatrix')`

2. For raw UMI counts, from your Seurat object:
`data <- as(as.matrix(shox2crepos_mtmg[["RNA"]]@counts), 'sparseMatrix')`

3. For **stress-free** data extraction from your Seurat object 😄 use the following (this example assumes you want count-data:

`data <- GetAssayData(object = shox2crepos_mtmg, slot = "counts")`

I hope that helps 

🐉

**Comment by naixiangxiaozi** [comment]
Thank you so much for your help. One more thing I want to make sure is if I import Seurat object into monocle, did I still need to do the distribution for my data by using the code
"HSMM <- newCellDataSet(count_matrix,
                phenoData = pd,
                featureData = fd,
                expressionFamily=negbinomial.size())" .
For the tutorial make me confused about whether I should do this step for it is marked required while the code #do not run.
And it is said we should not normalize our data ourself, but if we import Seurat data into monocle, the data must be already normalized?

Much appreciated,
Hua
________________________________

**Comment by ncalistri** [comment]
The standard Seurat analysis pipeline leaves the data accessible in three different forms:

1. 'counts' - this is the original count matrix that you built the Seurat object with

2. 'data' - this is the normalized gene expression data, using whatever normalization techniques you performed with the NormalizeData() function

3. 'scale.data' - this is the normalized and scaled data, generated with the ScaleData() function

When accessing your data with the 'GetAssayData' function you can set the 'slot' argument to pull from any of these three data slots. Note that depending on your preprocessing steps, the 'data' and 'scale.data' slots may only include the variable features and not the full gene/feature list.

**Comment by Dragonmasterx87** [comment]
@ncalistri [this](https://en.wikipedia.org/wiki/Cookie) is for you. 🍪

**Comment by naixiangxiaozi** [comment]
Thank you so much for your help. One more thing I want to make sure is if I import Seurat object into monocle, did I still need to do the distribution for my data by using the code
"HSMM <- newCellDataSet(count_matrix,
                phenoData = pd,
                featureData = fd,
                expressionFamily=negbinomial.size())" .
For the tutorial make me confused about whether I should do this step for it is marked required while the code #do not run.
And it is said we should not normalize our data ourself, but if we import Seurat data into monocle, the data must be already normalized?

Much appreciated,
Hua

________________________________

**Comment by Dragonmasterx87** [comment]
According to my understanding, this depends upon if you are using (extraction via GetAssayData) normalized, scaled or raw UMI counts. 

Now depending on how and which data you are using, you can use different monocle parameters to construct your newCellDataSet. read here for clarification on what a [newCellDataSet](http://cole-trapnell-lab.github.io/monocle-release/docs/#getting-started-with-monocle) is. Now monocle has 4 different types of data distribution, which you can specify. They are:

1. negbinomial.size()
2. negbinomial()
3. tobit()
4. gaussianff()

Each has its own description which you can read more about [here](http://cole-trapnell-lab.github.io/monocle-release/docs/#choosing-a-distribution-for-your-data-required). Lastly generating a Monocle cds or cell data set is essential for performing ordering calculations, so I think it's necessary, I couldn't find where it says not to run.

someone else please correct me if I'm wrong.

**Comment by Yale73** [comment]
Thanks for your code @ncalistri , but I ran a new issue:  could not find function "newCellDataSet", no matter which one I installed or used, I got the same errors again and again[#379](https://github.com/cole-trapnell-lab/monocle-release/issues/379). Could you help me solve it? Thanks again.

**Comment by ondina-draia** [comment]
I have the same error here with newCellDataSet that can't be found even if monocle3 is installed and the library called ...  I don't know if it's because I installed Monocle3 through conda or if there's something wrong with one of the dependecies ...

**Comment by Marcus-NEXUS** [comment]
@happar73 @ondina-draia
> I have the same error here with newCellDataSet that can't be found even if monocle3 is installed and the library called ... I don't know if it's because I installed Monocle3 through conda or if there's something wrong with one of the dependecies ...

From what I can tell, the function is now called `new_cell_data_set`. (I was having the same issue.)

**Comment by JayalalKJ** [comment]
> @kgerner Ok I'm not sure if I understand your current situation.. So if you are talking about generating heatmaps based on the pseudotemporal plots, then maybe I can help. If you want to make heatmaps of DE gene expression, use Seurat, its the best. Use monocle only for pseudotemporal gene expression analysis. Let me show you what I'm doing:
> 
> ```
> seuratX <- analysis.file
> 
> #Extract data, phenotype data, and feature data from the SeuratObject
> data <- as(as.matrix(seuratX@assays$RNA@data), 'sparseMatrix')
> 
> pd <- new('AnnotatedDataFrame', data = seuratX@meta.data)
> 
> fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
> fd <- new('AnnotatedDataFrame', data = fData)
> 
> #Construct monocle cds
> HSMM <- newCellDataSet(data,
>                               phenoData = pd,
>                               featureData = fd,
>                               #lowerDetectionLimit = 0.5,
>                               expressionFamily = uninormal())# since I have already normalized, thresholded and scalled in Suerat v3.0.0.9150
> 
> #View data
> pData(HSMM)
> fData(HSMM)
> 
> 
> #Run ordering algorithm
> var_genes <- seuratX[["RNA"]]@var.features
> ordering_genes <- var_genes
> 
> HSMM <- setOrderingFilter(HSMM, ordering_genes)
> print(dim(exprs(HSMM)))
> 
> ## reduce dimension - do not normalize or include pseudo count. Use monocle scaling
> HSMM <- reduceDimension(HSMM,norm_method="none", 
>                         reduction_method="DDRTree",
>                         max_components=4,
>                         scaling=TRUE,
>                         verbose=TRUE,
>                         pseudo_expr=0)
> 
> # First decide what you want to color your cells by
> print(head(pData(HSMM)))
> 
> ## order cells change colors and theta to match your plot
> HSMM <- orderCells(HSMM)
> plot_cell_trajectory(HSMM, 
>                      color_by = "seurat_clusters",
>                      theta = -15,
>                      show_branch_points = FALSE,
>                      show_tree = TRUE,
>                      cell_size = 4) + scale_color_manual(breaks = c("X", "Y", "Z"), 
>                                                          values=c("red",
>                                                                         "green",
>                                                                         "blue")) + theme(legend.position = "right")
> 
> # now onwards to pseudotemporal plots
> genex <- c("geneX", "geneY")
> 
> sig_gene_names <- (genex)
> head(sig_gene_names)
> pseudotemporalplot <- plot_pseudotime_heatmap(HSMM[sig_gene_names],
>                         num_clusters = 9, 
>                         cores = 4,
>                         hmcols = NULL,
>                         show_rownames = T)
> 
> pseudotemporalplot
> ```
> 
> Hope that Helps!!!
![image](https://user-images.githubusercontent.com/40278254/84001008-13abb580-a966-11ea-8860-76a98c3194e4.png)

Hi,
What really #Run ordering algorithm is doing here? I got some empty cell. not sure I'm correct with my analysis  ?

```{r}
#Run ordering algorithm
var_genes <- seuratX[["RNA"]]@var.features
ordering_genes <- var_genes
```
