### ISSUE TITLE
Differential Gene expression between clusters 

### ISSUE THREAD

**Issue by verma014** [cole-trapnell-lab/monocle-release#28]
Hi,
I have 10X data where I am able to segregate my data into 5 different clusters. 3 of those clusters are very segregated and two are partly overlapping. I have a few genes that are high in one population and low in the other. I would like to perform DGE between just the two closely related populations. 
The "differentialGeneTest" shows the DGE but does not indicate which clusters a certain target is greatly expressed in. I could subset each set of clusters and run "differentialGeneTest" individually, but that seems like a long workaround as you increase the number of clusters. 
Any idea what the best method for doing DGE between some specific clusters?
Thanks

**Comment by Xiaojieqiu** [comment]
Hi Verma, 

It seems to me you are asking two questions: 
1) you are interested in which DE gene is enriched in which cluster 
2) you are interested in performing DEG across multiple clusters

For the first question, you may simply calculate the folder change for DEG between two clusters and then decide which gene is enriched in which cluster. In our next release of Monocle, We will provide an additional column from the DEG test result to store the effect size calculated from the differential gene test. 

For your second question, if you simply mean you want to identifying all genes changes across all clusters, you could just use the cluster identifier for all cells and perform DEG against that identifier. 
However, if you are talking about identifying DEG between different pairs of clusters of cells, we could in our next release provide a simple helper function to perform DEG for all possible combination of pairwise clusters (although this is time consuming and not something most people would like to do). 

Hope this helps and thanks!

**Comment by verma014** [comment]
Hi Thanks for the response.
I actually meant that I want to compare specific cluster. For examples, if I have 5 clusters, I would just like to find the DEG only between cluster 2&3. 
I am currently using the following command-
diff_test_res <- differentialGeneTest(FilteredCells[expressed_genes,],
                                      fullModelFormulaStr="~num_genes_expressed", cores = detectCores())
This gives me DEG between all clusters. Since cluster 2&3 are much more similar than all the other clusters, I get a large list of genes that are differentially expressed with no way to figure out which genes are differentially expressed in cluster 2 vs 3. 

The effect size calculated from the differential gene test would also be a great addition! 

Thanks

**Comment by Xiaojieqiu** [comment]
quick answer. You can subset your cds when you do the DEG test. for example the following code will do the trick.
 `diff_test_res <- differentialGeneTest(FilteredCells[expressed_genes, pData(FilteredCells)$Cluster %in% c(2, 3)],
fullModelFormulaStr="~num_genes_expressed", cores = detectCores())`

**Comment by Xiaojieqiu** [comment]
BTW, member in our lab pointed that you may mean to use 

> fullModelFormulaStr="~ Cluster "
instead of 
> fullModelFormulaStr="~ num_genes_expressed "

**Comment by verma014** [comment]
Perfect! That was exactly what I was looking for. 
Thanks for the very quick response.

**Comment by sgmccalla** [comment]
Related to this, is it possible to subset data from an individual cluster? 
So for example, if clusterCells had an output of 7 clusters, how would I save cluster 2 in a separate data frame so that I might perform some separate analyses only on cluster 2?
Thank you
