### ISSUE TITLE
Export 3D coordinates to Blender

### ISSUE THREAD

**Issue by JBreunig** [cole-trapnell-lab/monocle-release#281]
Thank you for the wonderful packages that you have developed.

Can you give some insight as to the steps taken to export the UMAP to 3d packages for visualization and animation?
https://twitter.com/coletrapnell/status/1098335248444665856

**Comment by gnar5tar** [comment]
If you "plot_3d_cell_trajectory", then you can save that 3d object as an OBJ file extension and import that into Blender. But that's about as far as I've gotten. OBJ's apparently can't save colors or text so right now its just a higher res grey 3D UMAP.

**Comment by JBreunig** [comment]
Ok, I see now and got it working...thanks so much!

**Comment by gnar5tar** [comment]
@JBreunig Have you figured out how to retain color/cluster information from the 3D trajectory to blender?

**Comment by JBreunig** [comment]
No, looking at the function options and notations over the weekend, it appears like it isn't possible.  I'm guessing that they may have manually colored them in Blender.  I hope that I'm wrong ;)

**Comment by gnar5tar** [comment]
One option that has been sort of working is subsetting each individual population and replotting the 3D trajectory without recalculating the trajectory. Then you can import them into blender and color each population individually. The nice thing is it keeps its position in space relative to the original 3D trajectory. So hopefully this helps you out! 

My only issue is for some random reason when I subset a particular population it either refuses to plot or plots a fraction of the cells. Some populations work great, and some completely fail - pretty frustrating when its the same code.

**Comment by JBreunig** [comment]
Great suggestion, thanks!
