### ISSUE TITLE
An issue with monocle3 installation

### ISSUE THREAD

**Issue by FTD2018** [cole-trapnell-lab/monocle-release#285]
I'm trying to install monocle 3, everything was fine until the command:

devtools::install_github("cole-trapnell-lab/monocle-release", ref="monocle3_alpha").

And the ERROR came out:

Error : ()'louvain.R'8
ERROR: unable to collate and parse R files for package 'monocle'
* removing 'C:/Users/LENOVO/R/win-library/3.5/monocle'
* restoring previous 'C:/Users/LENOVO/R/win-library/3.5/monocle'

I really don't know how to solve the problem. Is the version of R software in my computer not suitable?

My R version is 
R version 3.5.3 (2019-03-11) -- "Great Truth"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

Many thanks for any suggestions.

**Comment by dwucsf** [comment]
Here's my code for installing monocle 3:

#remove and re-install monocle 3

remove.packages('monocle')

source("http://bioconductor.org/biocLite.R")
biocLite()
biocLite("monocle")

install.packages("devtools") 
library(devtools)
devtools::install_github("cole-trapnell-lab/DDRTree", ref="simple-ppt-like", force = TRUE)
devtools::install_github("cole-trapnell-lab/L1-graph", force = TRUE)

install.packages("reticulate")
library(reticulate)
py_install('umap-learn', pip = T, pip_ignore_installed = T) # Ensure the latest version of UMAP is installed
py_install("louvain")

remove.packages('VGAM')
install_version("VGAM", version = "1.0-6", repos = "http://cran.us.r-project.org")

devtools::install_github("cole-trapnell-lab/monocle-release", ref="monocle3_alpha", force = TRUE)

library(monocle)
package.version("monocle")
library(VGAM)

**Comment by FTD2018** [comment]
> 
> 
> Here's my code for installing monocle 3:
> 
> #remove and re-install monocle 3
> 
> remove.packages('monocle')
> 
> source("http://bioconductor.org/biocLite.R")
> biocLite()
> biocLite("monocle")
> 
> install.packages("devtools")
> library(devtools)
> devtools::install_github("cole-trapnell-lab/DDRTree", ref="simple-ppt-like", force = TRUE)
> devtools::install_github("cole-trapnell-lab/L1-graph", force = TRUE)
> 
> install.packages("reticulate")
> library(reticulate)
> py_install('umap-learn', pip = T, pip_ignore_installed = T) # Ensure the latest version of UMAP is installed
> py_install("louvain")
> 
> remove.packages('VGAM')
> install_version("VGAM", version = "1.0-6", repos = "http://cran.us.r-project.org")
> 
> devtools::install_github("cole-trapnell-lab/monocle-release", ref="monocle3_alpha", force = TRUE)
> 
> library(monocle)
> package.version("monocle")
> library(VGAM)

Thanks for your code. I have installed the monocle 3 in the server successfully. 

But there is still a problem in my own computer, may be caused by the broken conda environment. 
I will figure it out later.

Thanks!

**Comment by aina91** [comment]
could u please tell me whether monocle version 2.99.3 is monocle version 3 beta?
