### ISSUE TITLE
RStudio crashes when I try to use newCellDataSet()

### ISSUE THREAD

**Issue by VermillionAzure** [cole-trapnell-lab/monocle-release#3]
I've tried doing this with Monocle many times now, and it doesn't seem to work. It works outside of RStudio, but it crashes only if I run it in RStudio.

I have no slightest clue why; I've tried to make sure that the data is indeed correct and conforms to the AnnotatedDataFrame requirements.

I've included a link to the data I've used for Monocle. http://filebin.ca/2SZMzFp2gDxX

**Comment by ctrapnell** [comment]
This issue is caused (in our experience) because of a bug in igraph, one of Monocle's dependencies. See here for more info:

https://groups.google.com/forum/#!topic/monocle-users/sTq8vYyJA78

Installing igraph from the igraph github repo appears to work around the issue.

**Comment by X-Buring** [comment]
Thanks for your E-mail. I had already made it work although I still don't know why it crashes. 

------------------
王昊
清华大学计算机系计24班
Computer Science and Technology, Tsinghua University
TEL：+8613240094344
Email：wanghao1993333@gmail.com



 




------------------ Original ------------------

**Comment by jacobkimmel** [comment]
This fixed my issue, thanks Cole!
