### ISSUE TITLE
progenitor_method="omit" for buildBranchCellDataSet

### ISSUE THREAD

**Issue by dpcook** [cole-trapnell-lab/monocle-release#30]
Currently the buildBranchCellDataSet function in BEAM() and plot_genes_branched_heatmap() handle the progenitor branch with either the "duplicate" or "sequential" progenitor_method option. It may be nice to have an option that omits the progenitor branch and only models from the selected branch point forward. 

I've found that the row clustering in the branched heatmap can sometimes be driven by expression dynamics in the progenitor branch. Sometimes it may be more appropriate to focus on solely expression patterns after the branch point (eg. Up in Branch A, Down in Branch B)

**Comment by Xiaojieqiu** [comment]
Hi David, 
Thanks a lot for your suggestion. When we design BEAM, we want to identify genes diverge between two lineages after the branch point, therefore we expect the kinetic curves for the significant BEAM genes from two lineages share the same expression pattern in the progenitor state and gradually diverge after that. This is related to the pitch-fork bifurcation in dynamic systems (https://en.wikipedia.org/wiki/Pitchfork_bifurcation). 

We will consider whether or not we should have an option for making the branched heatmap without considering the progenitor state. If this is what you want, for now you can try to subset the cds to each of the branch after branch points and then use plot_genes_in_pseudotime to make two separate heatmaps for each lineage. 

In addition, in our next monocle release we will have new features to create multi-lineage kinetic curves as well as branched heatmaps.
