### ISSUE TITLE
monocle3 cellranger

### ISSUE THREAD

**Issue by leafyes** [cole-trapnell-lab/monocle-release#306]

**Comment by hpliner** [comment]
Thank you for submitting a bug report. Your report has insufficient information for us to address it. Please respond with the information requested in the bug report issue template. At minimum, please include: 

1. The code you ran that generated the error
2. The output of the call - and what was expected
3. The output of traceback()
4. The output of sessionInfo()

We will close this issue - when you answer with this further information, please reopen the issue.

- Monocle3 Dev Team
