### ISSUE TITLE
Error when using reduceDimension

### ISSUE THREAD

**Issue by ahmedmahfouz** [cole-trapnell-lab/monocle-release#32]
Hi,
I am trying to order cells using monocle, but I get an error at the dimensionality reduction step (reduceDimension) . If I look at the verbose output, it seems this happens at iteration 19 and the error says:
Clearing MST sparse matrix
Setting up MST sparse matrix with 1225
Error in colnames(Y)[closest_vertex] : invalid subscript type 'list'

Did anyone see this error before? Do you have any idea what might cause such an error?

**Comment by Xiaojieqiu** [comment]
This error seems to happen at the step where we project each cell in low dimension to the principal graph.  I didn't confront this error before, would you mind to share a piece of the data for reproducing your error? 

Thanks!

**Comment by Xiaojieqiu** [comment]
I suppose this issue is not relevant anymore and close it for now. please provide reproducible examples if the similar issue comes out
