### ISSUE TITLE
Missing descriptions for some arguments in reduceDimension()

### ISSUE THREAD

**Issue by m113track** [cole-trapnell-lab/monocle-release#33]
The descriptions for the arguments relative_expr, auto_param_selection and scaling are missing from the help for reduceDimension.
What do changing these arguments do?

**Comment by Xiaojieqiu** [comment]
We will add the documentation for all those arguments. We forget to add the documentation in the previous release, sorry about that. 

auto_param_selection: when this argument set to TRUE (default), it will automatically calculate the proper value for the ncenter (number of centroids) parameters which will be passed into DDRTree call. 
scale:  when this argument set to TRUE (default), it will scale each gene before running trajectory reconstruction.

For relative_expr: when this argument set to TRUE (default), we intent to convert the expression into relative expression. I believe this is a defunct and may remove in future release. 

Hope this helps!
