### ISSUE TITLE
Seurat object can't be imported into monocle:cannot coerce class ‘structure("AnnotatedDataFrame", package = "Biobase")’ to a data.frame

### ISSUE THREAD

**Issue by Sophia409** [cole-trapnell-lab/monocle-release#343]
@ctrapnell Hello, recently monocle 3 has upgraded.And after I modify the code that is used to import seurat  object according to new new_cell_data_set function,it gave errors. Can you give me some help?Thank you very much.
>
> #262 how to import seurat object
> data <- Merge.integrated@assays$RNA@data
> cell_metadata <- new('AnnotatedDataFrame', data = Merge.integrated@meta.data)
> fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
> gene_metadata <- new('AnnotatedDataFrame', data = fData)
> #Construct monocle cds
> tdcds <-  new_cell_data_set(data,
> cell_metadata = cell_metadata,
> gene_metadata = gene_metadata
> )`

`Error in as.data.frame.default(from) : 
  cannot coerce class ‘structure("AnnotatedDataFrame", package = "Biobase")’ to a data.frame`

**Comment by amar1406** [comment]
I had the same issue with importing. Thanks for sharing this code!
I added two lines of codes and it works for now.

You just need to convert AnnotatedDataFrame into data.frame just before you construct the object:

```R
data <- Merge.integrated@assays$RNA@data
cell_metadata <- new('AnnotatedDataFrame', data = Merge.integrated@meta.data)
fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
gene_metadata <- new('AnnotatedDataFrame', data = fData)

gene_metadata <- as(gene_metadata, "data.frame")
cell_metadata <- as(cell_metadata, "data.frame")

#Construct monocle cds
tdcds <- new_cell_data_set(data,
cell_metadata = cell_metadata,
gene_metadata = gene_metadata
)
```

Not sure if anything downstream would be affected due to loss of annotation. So far everything working fine!

**Comment by Sophia409** [comment]
Hi:
Thanks for sharing this code，too!
I'm able to run Monocle 3 with Seurat 3's RNA cells/counts, but I'm trying to construct my CDS in such a way that it contains original RNA count and integrated count data. I haven't figured this out. Have you?


| |
yuhong
|
|
yuhongruoyi@163.com
|
签名由网易邮箱大师定制
On 6/13/2019 12:00，amar1406<notifications@github.com> wrote：

I had the same issue with importing. Thanks for sharing this code!
I added two lines of codes and it works for now.

You just need to convert AnnotatedDataFrame into data.frame just before you construct the object:

data<-Merge.integrated@assays$RNA@datacell_metadata<- new('AnnotatedDataFrame', data=Merge.integrated@meta.data)
fData<-data.frame(gene_short_name= row.names(data), row.names= row.names(data))
gene_metadata<- new('AnnotatedDataFrame', data=fData)

gene_metadata<- as(gene_metadata, "data.frame")
cell_metadata<- as(cell_metadata, "data.frame")

#Construct monocle cdstdcds<- new_cell_data_set(data,
cell_metadata=cell_metadata,
gene_metadata=gene_metadata
)

Not sure if anything downstream would be affected due to loss of annotation. So far everything working fine!

**Comment by Sophia409** [comment]
> 
> 
> I had the same issue with importing. Thanks for sharing this code!
> I added two lines of codes and it works for now.
> 
> You just need to convert AnnotatedDataFrame into data.frame just before you construct the object:
> 
> ```r
> data <- Merge.integrated@assays$RNA@data
> cell_metadata <- new('AnnotatedDataFrame', data = Merge.integrated@meta.data)
> fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
> gene_metadata <- new('AnnotatedDataFrame', data = fData)
> 
> gene_metadata <- as(gene_metadata, "data.frame")
> cell_metadata <- as(cell_metadata, "data.frame")
> 
> #Construct monocle cds
> tdcds <- new_cell_data_set(data,
> cell_metadata = cell_metadata,
> gene_metadata = gene_metadata
> )
> ```
> 
> Not sure if anything downstream would be affected due to loss of annotation. So far everything working fine!

Hi: Thanks for sharing this code，too! I'm able to run Monocle 3 with Seurat 3's RNA cells/counts, but I'm trying to construct my CDS in such a way that it contains original RNA count and integrated count data. I haven't figured this out. Have you?
