### ISSUE TITLE
igraph error when running order_cells

### ISSUE THREAD

**Issue by ryandhindsa** [cole-trapnell-lab/monocle-release#345]
Hi there, whenever I run order_cells, I get the following error:
Error in as.igraph.vs(graph, v) : Invalid vertex names

Is this a known issue?

**Comment by hpliner** [comment]
Hello,

This issue appears to be an issue about our new package, Monocle 3. Please post any issues for Monocle 3 to the monocle3 repository at https://github.com/cole-trapnell-lab/monocle3.

- Monocle 3 Development team
