### ISSUE TITLE
residualModelFormulaStr in Monocle 3

### ISSUE THREAD

**Issue by dwucsf** [cole-trapnell-lab/monocle-release#347]
I'm trying to perform batch correction using residualModelFormulaStr in Monocle 3. Is residualModelFormulaStr compatible with reduceDimension step in Monocle 3? Is this the correct way of batch-correcting within Monocle 3? I'm importing Seurat 3 data and setting residualModelFormulaStr="orig.ident"

cds <- reduceDimension(cds, reduction_method = 'UMAP', residualModelFormulaStr = "orig.ident") 

Any help would be appreciated! Thanks!

**Comment by lb15** [comment]
hey! batch correction in monocle 3 is in preprocessing. from the tutorial page:

```
cds = preprocess_cds(cds, num_dim = 100, residual_model_formula_str = "~ plate")
cds = reduce_dimension(cds)
```

**Comment by dwucsf** [comment]
Thanks! It worked. Do you know why the '~' is needed in the residual_model_formula_str parameter?

**Comment by hpliner** [comment]
Hello,

This issue appears to be an issue about our new package, Monocle 3. Please post any issues for Monocle 3 to the monocle3 repository at https://github.com/cole-trapnell-lab/monocle3.

- Monocle 3 Development team
