### ISSUE TITLE
Error during differentialGeneTest calculations

### ISSUE THREAD

**Issue by ashwinikumarkulkarni** [cole-trapnell-lab/monocle-release#35]
I am using 10X data.

**print(head(fData(MCX2MCX3)))**
                                   id gene_short_name use_for_ordering
ENSMUSG00000000001 ENSMUSG00000000001           Gnai3            FALSE
ENSMUSG00000000003 ENSMUSG00000000003            Pbsn            FALSE
ENSMUSG00000000028 ENSMUSG00000000028           Cdc45            FALSE
ENSMUSG00000000031 ENSMUSG00000000031             H19            FALSE
ENSMUSG00000000037 ENSMUSG00000000037           Scml2            FALSE
ENSMUSG00000000049 ENSMUSG00000000049            Apoh            FALSE
                   num_cells_expressed
ENSMUSG00000000001                1546
ENSMUSG00000000003                   0
ENSMUSG00000000028                  56
ENSMUSG00000000031                  56
ENSMUSG00000000037                  96
ENSMUSG00000000049                  12

**print(head(pData(MCX2MCX3)))**
                                        barcode library age genotype
MCX2_AAACCTGCATAAAGGT-1 MCX2_AAACCTGCATAAAGGT-1    MCX2  P7      CTL
MCX2_AAACCTGCATTTCACT-1 MCX2_AAACCTGCATTTCACT-1    MCX2  P7      CTL
MCX2_AAACCTGGTGTTCTTT-1 MCX2_AAACCTGGTGTTCTTT-1    MCX2  P7      CTL
MCX2_AAACGGGAGACTTTCG-1 MCX2_AAACGGGAGACTTTCG-1    MCX2  P7      CTL
MCX2_AAACGGGAGAGGGCTT-1 MCX2_AAACGGGAGAGGGCTT-1    MCX2  P7      CTL
MCX2_AAACGGGAGGTGATAT-1 MCX2_AAACGGGAGGTGATAT-1    MCX2  P7      CTL
                        num_genes_expressed
MCX2_AAACCTGCATAAAGGT-1                3600
MCX2_AAACCTGCATTTCACT-1                2007
MCX2_AAACCTGGTGTTCTTT-1                4521
MCX2_AAACGGGAGACTTTCG-1                1512
MCX2_AAACGGGAGAGGGCTT-1                2322
MCX2_AAACGGGAGGTGATAT-1                 569

**diff_test_res <- differentialGeneTest(MCX2MCX3, fullModelFormulaStr="~genotype")**
gives error as below

<simpleError in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),     NULL) else NULL): 'data' must be of a vector type, was 'NULL'>
<simpleError in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),     NULL) else NULL): 'data' must be of a vector type, was 'NULL'>
<simpleError in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),     NULL) else NULL): 'data' must be of a vector type, was 'NULL'>
..
..
..
..

The resulting dataframe/matrix has all FAIL with p-val and q-val equal to 1.

**Comment by Xiaojieqiu** [comment]
Those errors result from the VGLM fitting step to me. Can you check the expression data you have by 
`exprs(MCX2MCX3)[1:5, 1:5]`. It seems like your data included NULL for some genes / cells

**Comment by ashwinikumarkulkarni** [comment]
Thank you for your comment! Please see below. 

```
exprs(MCX2MCX3)[1:5, 1:5]
                   MCX2_AAACCTGCATAAAGGT-1 MCX2_AAACCTGCATTTCACT-1
ENSMUSG00000000001                       1                       1
ENSMUSG00000000003                       0                       0
ENSMUSG00000000028                       0                       0
ENSMUSG00000000031                       0                       0
ENSMUSG00000000037                       0                       0
                   MCX2_AAACCTGGTGTTCTTT-1 MCX2_AAACGGGAGACTTTCG-1
ENSMUSG00000000001                       2                       0
ENSMUSG00000000003                       0                       0
ENSMUSG00000000028                       0                       0
ENSMUSG00000000031                       0                       0
ENSMUSG00000000037                       0                       0
                   MCX2_AAACGGGAGAGGGCTT-1
ENSMUSG00000000001                       2
ENSMUSG00000000003                       0
ENSMUSG00000000028                       0
ENSMUSG00000000031                       0
ENSMUSG00000000037                       0
```

**Comment by Xiaojieqiu** [comment]
I think, again, this error results from the fact that the data including some non-numeric data (like NA or NaN, etc). I will close it for now. Please let me know if this resolves your issue

**Comment by ChengchenZhao** [comment]
Hi, I got the same error when performing differentialGeneTest() in an Ubuntu 16.04.2 system. But It run successfully in the MacOs 10.10.5 system. And I ensured that there is no NA in my input matrix. So maybe this error occurred by the differences of the operating system?
