### ISSUE TITLE
Not re-encodable characters when installing

### ISSUE THREAD

**Issue by juychen** [cole-trapnell-lab/monocle-release#351]
When installing the package from github using devtools, the system raised an error 
"unable to re-encode 'cluster_cells.R' lines 130, 146, 147, 150, 151"
Then I clone the project file to my machine, delete these annotation rows and the installation is successful.

**Comment by Lyuzu** [comment]
I met the same error as yours.

**Comment by hpliner** [comment]
Hello,

This issue appears to be an issue about our new package, Monocle 3. Please post any issues for Monocle 3 to the monocle3 repository at https://github.com/cole-trapnell-lab/monocle3.

- Monocle 3 Development team
