### ISSUE TITLE
plot_cells() error when using a specific gene list

### ISSUE THREAD

**Issue by jentiger82** [cole-trapnell-lab/monocle-release#355]
I get the following error when I try to run plot_cells() with a specific marker gene list for visualization:

> plot_cells(nbh_cds, genes = ctip2_genes, label_cell_groups = FALSE, show_trajectory_graph = FALSE)
Error in plot_cells(nbh_cds, genes = ctip2_genes, label_cell_groups = FALSE,  :
  trying to get slot "x" from an object of a basic class ("matrix") with no slots

The problem is caused by:
cds_exprs@x = round(cds_exprs@x)
in this section of plot_cells():
if (nrow(markers_rowData) >= 1) {
            cds_exprs <- SingleCellExperiment::counts(cds)[row.names(markers_rowData),
                , drop = FALSE]
            cds_exprs <- Matrix::t(Matrix::t(cds_exprs)/size_factors(cds))
            if (!is.null(dim(genes)) && dim(genes) >= 2) {
                genes = as.data.frame(genes)
                row.names(genes) = genes[, 1]
                genes = genes[row.names(cds_exprs), ]
                agg_mat = as.matrix(my.aggregate.Matrix(cds_exprs,
                  as.factor(genes[, 2]), fun = "sum"))
                agg_mat = t(scale(t(log10(agg_mat + 1))))
                agg_mat[agg_mat < -2] = -2
                agg_mat[agg_mat > 2] = 2
                markers_exprs = agg_mat
                markers_exprs <- reshape2::melt(markers_exprs)
                colnames(markers_exprs)[1:2] <- c("feature_id",
                  "cell_id")
                if (is.factor(genes[, 2]))
                  markers_exprs$feature_id = factor(markers_exprs$feature_id,
                    levels = levels(genes[, 2]))
                markers_exprs$feature_label <- markers_exprs$feature_id
                norm_method = "size_only"
                expression_legend_label = "Expression score"
            }
            else {
                cds_exprs@x = round(cds_exprs@x)
                markers_exprs = matrix(cds_exprs, nrow = nrow(markers_rowData))
                colnames(markers_exprs) = colnames(SingleCellExperiment::counts(cds))
                row.names(markers_exprs) = row.names(markers_rowData)
                markers_exprs <- reshape2::melt(markers_exprs)
                colnames(markers_exprs)[1:2] <- c("feature_id",
                  "cell_id")
                markers_exprs <- merge(markers_exprs, markers_rowData,
                  by.x = "feature_id", by.y = "row.names")
                markers_exprs$feature_label <- as.character(markers_exprs$gene_short_name)
                markers_exprs$feature_label <- ifelse(is.na(markers_exprs$feature_label) |
                  !as.character(markers_exprs$feature_label) %in%
                    markers, as.character(markers_exprs$feature_id),
                  as.character(markers_exprs$feature_label))
                markers_exprs$feature_label <- factor(markers_exprs$feature_label,
                  levels = markers)
                if (norm_method == "size_only")
                  expression_legend_label = "Expression"
                else expression_legend_label = "log10(Expression)"
            }
        }
    }

**Comment by hpliner** [comment]
Hello,

This issue appears to be an issue about our new package, Monocle 3. Please post any issues for Monocle 3 to the monocle3 repository at https://github.com/cole-trapnell-lab/monocle3.

- Monocle 3 Development team
