### ISSUE TITLE
How to extract pseudotime coordinates (components) for each cell?

### ISSUE THREAD

**Issue by Close-your-eyes** [cole-trapnell-lab/monocle-release#356]
Dear all,

I have been trying and reading for some time now but I cannot find any useful hint. 

How can extract the coordinates of cells after running "orderCells" which gives me the trajectories of cell development?

I am not talking about the lines that I see when running "plot_cell_trajectory" but I am referring to the coordinates of the dots (= cells) in this plot. So, values for Component 1 and Component 2. They must be somewhere. They are just like coordinates from dimension reduction.

Thanks for your advice.

**Comment by Close-your-eyes** [comment]
Okay, one way is to extract them from the ggplot object (see below), which is generated by plot_cell_trajectory(). But that's stupid because you lose the barcodes (=names of your cells).

traj.plot <- plot_cell_trajectory(cds, ...)
point.data <- ggplot_build(traj.plot)$data[[2]]

So, how to get those information directly from the cds-object?

**Comment by Close-your-eyes** [comment]
Alright, thanks to everyone, here is how to do it:
traj.plot <- plot_cell_trajectory(cds, ...)
point.data <- ggplot_build(traj.plot)[["plot"]][["data"]]

In point.data you will find everything you need, cell barcodes, phenotype data, trajectory coordinates.
Good luck.

**Comment by Sophia409** [comment]
@Close-your-eyes @ctrapnell Hi,thank you for your share.Why do you extract pseudotime coordinates information for each cell?Did you use it to plot pseudotime plot by other package?If so,I'm really want to know how to do it.
I use Seurat batch corrected data to ordercells,so I can't get gene expression dynamic picture,including genes_branched_pseudotime and genes_branched_heatmap.So I'm wondering if I can extract pseudotime coordinates from pData(or named metadata,and export it to other package to do these plots.I can add the pseudotime metadata information Seurat object,but this package can't be used to do pseudotime plot.Do you have any experience？Hope your help.

**Comment by Close-your-eyes** [comment]
Hello Sophia,

yes I wanted to have more flexibility in the pseudotime plot, e.g. I have TCR clonotype data for my T cells and I wanted to know where in plot enriched clonotypes are situated. I used ggPlot2 and tidyverse for it.

So, in order to get Seurats processed data into monocle I followed the code from @Dragonmasterx87 (https://github.com/cole-trapnell-lab/monocle-release/issues/262). After ordering cells in monocle you can pull out the pseudotime coordinates with my code-snippets from above. Then you know which cell has which coordinates and hence you can connect (join) that with any other meta.data or phenotype data from Seurat.

Okay?

**Comment by Sophia409** [comment]
@Close-your-eyes 
Hello,thank you for your reply.I think what I do is similar as you,because I also followd the  code by @Dragonmasterx87 (#262).But now,I can only get these cell_trajectory pictures(picture I).What I still need is the genes_branched_pseudotime(as picture2 and 3) and genes_branched_heatmap picture(this can be done by Seurat manually).So do you have any experience how to do genes_branched_pseudotime picture by using the pseudotime coordinates given by monocle.Could you share your code here? I'm really confused because I'm just a newcomer to this analysis.
![图片](https://user-images.githubusercontent.com/30619010/61801597-a54f2900-ae61-11e9-9587-8f4ce0286595.png)
![图片](https://user-images.githubusercontent.com/30619010/61801842-0f67ce00-ae62-11e9-9751-bdb6d71bd7e4.png)
![图片](https://user-images.githubusercontent.com/30619010/61802258-bf3d3b80-ae62-11e9-9fb3-9aaaa594414a.png)

**Comment by veravevo** [comment]
Hi, @Close-your-eyes , thanks for your great work! I just did what you suggested, and realized the data_dim 1 and data_dim 2 I retrieved from the plotting exactly reflects the values from reducedDimS stored within the CellDataSet. So the easy way to get the  cell coordinates from the trajectory would be 

traj.coord<-reducedDimS(cds)

**Comment by mcap91** [comment]
Any idea how to do this with monocle3 functions? these are from the original monocle package.

**Comment by afaissa** [comment]
Probably there is a better way to do that, but for me that worked:

`pbuild <- plot_cells(cds, color_cells_by = "cluster", label_cell_groups=T, show_trajectory_graph = F, label_leaves=F, label_branch_points=F, graph_label_size=3, group_label_size = 4, cell_size = 1)
`
`UmapCDS <- data.frame(pbuild$data$sample_name,dim1 = pbuild$data$data_dim_1, dim2 = pbuild$data$data_dim_2, row.names = 1)
`
`head(UmapCDS)`

**Comment by mcap91** [comment]
I figured it out

`traj.coord<- cds_from_seurat@principal_graph_aux@listData[["UMAP"]][["pseudotime"]]`

I am using UMAP, but you can call whatever coordinates you used for projection and ptime graphing
