### ISSUE TITLE
top_markers error with monocle 3 v0.1.1

### ISSUE THREAD

**Issue by ZeldaMendelowitz** [cole-trapnell-lab/monocle-release#357]
I am using monocle 3 v0.1.1

When I run the following function:

marker_test_res = top_markers(cds, group_cells_by="partition", reference_cells=1000, cores=8)

I get the following error:

Error in diff(norm_mat@p) : 
  no slot of name "p" for this object of class "dgTMatrix" 

Any help with would be very much appreciated :)

**Comment by hpliner** [comment]
Hello,

This issue appears to be an issue about our new package, Monocle 3. Please post any issues for Monocle 3 to the monocle3 repository at https://github.com/cole-trapnell-lab/monocle3.

- Monocle 3 Development team

**Comment by SiwenX** [comment]
> Hello,
> 
> This issue appears to be an issue about our new package, Monocle 3. Please post any issues for Monocle 3 to the monocle3 repository at https://github.com/cole-trapnell-lab/monocle3.
> 
> * Monocle 3 Development team

Have you fixed this issue?

**Comment by jingchen-0927** [comment]
Have you fixed this issue? I also met the same bug, hope for solving way from you, Thanks so much.
