### ISSUE TITLE
object 'bg.300.loading' not found

### ISSUE THREAD

**Issue by deliasoto** [cole-trapnell-lab/monocle-release#362]
Hello,

I am trying to run:
cds <- preprocess_cds(cds, num_dim = 100, residual_model_formula_str = "~ bg.300.loading + bg.400.loading + bg.500.1.loading + bg.500.2.loading + bg.r17.loading + bg.b01.loading + bg.b02.loading")

But I get this Error
Error in eval(predvars, data, env) : object 'bg.300.loading' not found

Has anyone encounter this problem? I am working with 10X loaded data.
I'll appreciate any thoughts.
Thanks

**Comment by miguelreinacampos** [comment]
Hi deliasoto,
I have run into the same problem;

> fibros_monocle_cds <- preprocess_cds(fibros_monocle_cds, num_dim = 100, residual_model_formula_str = "~ bg.300.loading + bg.400.loading + bg.500.1.loading + bg.500.2.loading + bg.r17.loading + bg.b01.loading + bg.b02.loading")
Error in eval(predvars, data, env) : object 'bg.300.loading' not found

Were you able to troubleshoot this?
Thank you so much in advance

**Comment by hpliner** [comment]
Hello,

This issue appears to be an issue about our new package, Monocle 3. Please post any issues for Monocle 3 to the monocle3 repository at https://github.com/cole-trapnell-lab/monocle3.

- Monocle 3 Development team

**Comment by yihengp2** [comment]
> Hi deliasoto,
> I have run into the same problem;
> 
> > fibros_monocle_cds <- preprocess_cds(fibros_monocle_cds, num_dim = 100, residual_model_formula_str = "~ bg.300.loading + bg.400.loading + bg.500.1.loading + bg.500.2.loading + bg.r17.loading + bg.b01.loading + bg.b02.loading")
> > Error in eval(predvars, data, env) : object 'bg.300.loading' not found
> 
> Were you able to troubleshoot this?
> Thank you so much in advance

Hi, I met the same problem using the cds data loaded from 10X data. Have you solved this problem?

Thanks

**Comment by deliasoto** [comment]
Hi, no I stop trying I think the problem is that the variables "bg.300.loading + bg.400.loading + bg.500.1.loading + bg.500.2.loading + bg.r17.loading + bg.b01.loading + bg.b02.loading" are specific to the example dataset ... so I try to find a way of setting it up residual_model_formula_str according to my own dataset and I honestly could not find how ... 

After trying for several weeks I actually decide to give up on monocle and try a different package. I'm not a bioinformatician so I need something with better tutorials or more user support.

Good luck!
