### ISSUE TITLE
Inconsistent distribution of UMAP maps！

### ISSUE THREAD

**Issue by pengpengyang94** [cole-trapnell-lab/monocle-release#364]
The `RunUMAP` function in `Seurat` has the `set.seed` parameter to set the random seed of UMAP. 
In the `reduce_dimension` function in `monocle`, I didn't find the parameters to set the random seed, which would lead me to get a variety of UMAP graphical results. I want to get a repeatable result, how can I set it up?

**Comment by hpliner** [comment]
Hello,

This issue appears to be an issue about our new package, Monocle 3. Please post any issues for Monocle 3 to the monocle3 repository at https://github.com/cole-trapnell-lab/monocle3.

- Monocle 3 Development team
