### ISSUE TITLE
issue loading in 10x matrix files using load_cellranger_data using Monocle3

### ISSUE THREAD

**Issue by scideas** [cole-trapnell-lab/monocle-release#370]
Hi, 

I have all 3 files that are required for building the single-cell matrix successfully in Seurat3, including barcodes.tsv, features.tsv, & matrix.mtx.  I'm using the raw_feature_bc_matrix folder.

For reference, my directories are arranged as they'd appear as raw cell ranger output folders with the hope it could read in these files (and I used many other types of arrangements I found online), but no dice... I also examined the raw code for this function in monocle3 and I didn't see anything that made it appear my filenames are incorrect. 

As of now, these are the folder layouts I've tried: 
pipestance_path >outs > raw_feature_bc_matrix > *files are located here*
pipestance_path >outs > raw_feature_bc_matrix > mm10 > *files are located here*

Any glaring errors here?
Thanks,
Aaron

**Comment by hpliner** [comment]
Hello,

This issue appears to be an issue about our new package, Monocle 3. Please post any issues for Monocle 3 to the monocle3 repository at https://github.com/cole-trapnell-lab/monocle3.

- Monocle 3 Development team
