### ISSUE TITLE
Highlight specific cells

### ISSUE THREAD

**Issue by rahulnutron** [cole-trapnell-lab/monocle-release#382]
Thanks for developing monocle3.
I  have a query, is it possible to select cells based on expression of multiple genes and plot their location in the UMAP plot, something like WhichCells; and cells.highlight argument can do  in DimPlot in Seurat?

Thanks,
RS

**Comment by rahulnutron** [comment]
Able to find a temporary solution by identifying my cell (id) of interest from Seurat.

plot.data <- plot_cells(cds_combined)
p.data <- ggplot_build(plot.data)[["plot"]][["data"]]
pnt<-c(p.data["2h_AAATGGATCTGGTTGA",]$data_dim_1, p.data["2h_AAATGGATCTGGTTGA",]$data_dim_2)
pnt

plot_cells(cds_combined, color_cells_by = "orig.ident",
           show_trajectory_graph=FALSE,
           label_cell_groups=FALSE,
           label_leaves=FALSE) + geom_point(colour="gray")+geom_point(aes(x = pnt[1], y = pnt[2]),colour="red")

**Comment by hpliner** [comment]
Hello,

This issue appears to be an issue about our new package, Monocle 3. Please post any issues for Monocle 3 to the monocle3 repository at https://github.com/cole-trapnell-lab/monocle3.

Monocle 3 Development team

**Comment by ShubhamBansal06** [comment]
I was just wondering is there an added functionality now?
