### ISSUE TITLE
Error in UseMethod("depth") :    no applicable method for 'depth' applied to an object of class "NULL"

### ISSUE THREAD

**Issue by brianpenghe** [cole-trapnell-lab/monocle-release#39]
When I typed the following command I got that error:
> plot_cell_clusters(HSMM,1,2,color="cell_class")
Error in UseMethod("depth") : 
  no applicable method for 'depth' applied to an object of class "NULL"

And a blank figure popped up.

However, I typed it again and a normal plot appeared.

Any ideas about that?

**Comment by brianpenghe** [comment]
And I tried again. This time I got this:

> plot_cell_trajectory(HSMM_myo, color_by = "cell_class")
Error in grid.Call.graphics(C_upviewport, as.integer(n)) : 
  cannot pop the top-level viewport ('grid' and 'graphics' output mixed?)

And a blank figure popped up.

However, I typed it again and a normal plot appeared.

**Comment by trangthule** [comment]
Do have happen to know the reason? I have the same issue, couldn't find answers that I could understand. I then restarted R and it worked normally.

**Comment by Xiaojieqiu** [comment]
I believe this error is related to the ggplot package. For questions not directly related Monocle, you may find other sites are more proper to find answers or ask questions.  (for example see this: http://r.789695.n4.nabble.com/viewport-bug-in-2-8-0-Error-Cannot-pop-the-top-level-viewport-grid-and-graphics-output-mixed-td886103.html) If you ask here, providing necessary code / code to will be also needed by us to reproduce your error and figure out the issue.

**Comment by brianpenghe** [comment]
Hi Xiaojie,
I used exactly the codes provided in the manual.
