### ISSUE TITLE
can not extract the raw counts from the seuratobject

### ISSUE THREAD

**Issue by Shawn10312** [cole-trapnell-lab/monocle-release#392]
Hi,  
Is there something wrong in my Seurat package?

```
tmp_data = as.data.frame(pbmc@assays$RNA)

Error in as.data.frame.default(pbmc@assays$RNA) : 
  cannot coerce class ‘structure("Assay", package = "Seurat")’ to a data.frame
```

When I load the Seurat package, it says:

> Attaching package: ‘Seurat’
> 
> The following object is masked from ‘package:SummarizedExperiment’:
> 
>     Assays

What is the problem??

**Comment by rich-green-aifimmunology** [comment]
was there a solution for this?
