### ISSUE TITLE
Very slow `fit_models` with 59 gene x 452000 cells...

### ISSUE THREAD

**Issue by davemcg** [cole-trapnell-lab/monocle-release#398]
....how long should I expect `fit_models` to take with a 59 gene x 452000 cell object? It's been an hour and still not done.

also....I've got a full run with all 14000 genes against 452000 cells that is at 18 hours ...

**Comment by davemcg** [comment]
Some benchmarking

Cut down cells to about 50,000

59 x 50000
```
> tic()
> gene_fits_big <- fit_models(cds_subset_big, model_formula_str = "~cluster + batch")
> toc()
279.199 sec elapsed
```

59 x 50000 (remove batch from model)
```
> tic()
> gene_fits_big <- fit_models(cds_subset_big, model_formula_str = "~cluster ")
> toc()
199.423 sec elapsed
```

So adding more covariatesmoderately influence computation time.

Looks like it takes about 5 seconds per gene for 50,000 cells. 

I'll do more cells to see how the run-time changes.

Good news is that this process can be parallelized by running `n` genes at a time. I just would have to re-calculate the q-values.

**Comment by hpliner** [comment]
Hello,

This issue appears to be an issue about our new package, Monocle 3. Please post any issues for Monocle 3 to the monocle3 repository at https://github.com/cole-trapnell-lab/monocle3.

Monocle 3 Development team

**Comment by Lucyyang1991** [comment]
I also need to run fit_models with lots of genes, but the time is too long. Feeling frustrated...
