### ISSUE TITLE
orderCells(): Unable to allocate vector of size ~9000GB

### ISSUE THREAD

**Issue by VermillionAzure** [cole-trapnell-lab/monocle-release#4]
I'm sorry to bother twice in a day, but this is another showstopper bug that we've encountered when trying to use Monocle. I've tried to file a report about this before and closed it due to lack of precision with finding the issue, but since we've fixed the `newCellDataSet()` issue, I think it'll be better to pinpoint the cause of the issue.

We've been trying to use a ~23000x875 raw gene-sample dataset to test with Monocle. However, this problem still occurs even when trimming down to just a 25x25 dataset. The data set, dummy grouping factors, and code that we are using can be found (temporarily?) here: http://filebin.ca/2UGWtSOINFOc

The issue occurs within the `orderCells()` function. I've gone through the vignette on Bioconductor. In my debugging, I've been able to track down the vector problem to this `for` loop which contains the recursive call within the function: `extract_good_ordering()`:

```
        for (child in V(pq_tree)[nei(curr_node, mode = "out")]) {
                    p_level[[length(p_level) + 1]] <- extract_good_ordering_(pq_tree, 
                                                                            child, dist_matrix)
                  }
```

![monocle_error3](https://cloud.githubusercontent.com/assets/844699/12157949/d52c1466-b479-11e5-8e1b-7b15feb10402.png)

Even if I replace some of the deprecated functions for `nei()` into `.nei()`, the vector allocation still fails.

Given that the code for the P and Q nodes look similar, I'd assume it fails for both cases.

I don't know much about graph theory or how the code applies to such, but I was able to track it down to here. Given the (looks like) the appending of mode nodes to the graph with each recursion... Could it be a problem with the list depth?

My version of `igraph` is that hosted on GitHub at `igraph/rigraph@master`, pulled from and installed on 1/6/2016.

Thank you.

**Comment by sunnytsoiwave** [comment]
Hi!

I encounter the same problem.
Error: cannot allocate vector of size 2650077.9 Gb

Thank you!

**Comment by sunnytsoiwave** [comment]
I figured out the problem.
In my case, not all the cells express the genes that I want to use for ordering.
Therefore there will be many cells with the reduced dimension same among them.
This may cause an infinite loop to order them.

It worked after I subset the cells that only express the markers I want to use.
Thank you!

**Comment by VermillionAzure** [comment]
@sunnytsoiwave So you're saying there needs to be a filled row for every gene that you want to use for ordering?

**Comment by sunnytsoiwave** [comment]
I don't think you need that for every gene. But you need variation in the final reduced dimension.
Since I only ran it with 10 genes, some of the cells don't express those genes at all and have no variation in the reduced dimension.
After I remove the cell that didn't express these genes, the memory problem didn't come back again.
So I guess it's the problem.

**Comment by Xiaojieqiu** [comment]
I suppose this issue has been resolved and I will close it.
