### ISSUE TITLE
no slot of name "reducedDims"

### ISSUE THREAD

**Issue by nasalehi** [cole-trapnell-lab/monocle-release#409]
Dear all
I have R version 3.6.3 on my Win laptop and I installed monocle3 version 0.2.1 which has worked properly. I had to move to a Linux server that has the same R version because of my big data (30 k cells). But I got this error "no slot of name "reducedDims" for this object of class "cell_data_set" " that I have not gotten this error in my laptop.
Would you kindly help me with this problem?
Thanks a lot

**Comment by hpliner** [comment]
Hello,

This issue appears to be an issue about our new package, Monocle 3. Please post any issues for Monocle 3 to the monocle3 repository at https://github.com/cole-trapnell-lab/monocle3.

 Monocle 3 Development team
