### ISSUE TITLE
orderCells(): takes a long time

### ISSUE THREAD

**Issue by liuyifang** [cole-trapnell-lab/monocle-release#41]
Hi
Monocle works well on 10x dataset about 3k cells, but when I move on to larger dataset like about 30k cells, the `orderCells()` takes about 36 hours, I wonder whether this step can be paralleled? Thanks.

**Comment by Xiaojieqiu** [comment]
Hi Yifang,

Monocle 2 should be able to work on 30 k cells. Are you using the newest Monocle version? Are you using the ncenter argument in reduceDimension before running orderCells?

**Comment by liuyifang** [comment]
Hi Xiaojie,

At first, I am running Monocle 2.4.0 on my 16G memory MacBook using `reduceDimension(cds, max_components=2)`  and not changing other default argument, then RStudio crashed at `orderCells()` step, I guess it is because of lacking memory for 30k cells. So I move to Linux server with Monocle 2.2.0 and finished `orderCells()` step but it takes 36 hours as I described before. I am not sure whether Monocle 2.2.0  is OK. 
Another detail is after I finish  `reduceDimension()`  on my MacBook with Monocle 2.4.0 and save the session to R image, then I load this image on Linux server with Monocle 2.2.0 and go on to finish `orderCells()` step , I am also not sure whether it is OK to do this with different operating system and different version of Monocle.

**Comment by Xiaojieqiu** [comment]
Monocle is still under active development. The newest version would be the best choice. It is also a good practice to NOT mixing up different versions of the software when you analyzing the data. Let me know how long it will take for you to run this dataset with the newest Monocle 2 (https://github.com/cole-trapnell-lab/monocle-release) on your cluster.

**Comment by liuyifang** [comment]
I installed the newest Monocle 2.5.4 from github. It takes about 2.5 hours to run my latest 40k cells data. It is pretty fast compared to the previous one which I use mix versions of monocle and takes 36 hours.
The trajectory is a little bit simplified, which means it only has one brach, the previous mix version has a lot branches and is closer to my complex biological sample. 
> cds <- setOrderingFilter(cds, ordering_genes)
> cds <- reduceDimension(cds)
> cds <- orderCells(cds)

Currently I almost using default parameters for the analysis, whether there is any parameter I can set, like kmeans, I can determine there are n branches in the trajectory, If monocle has this parameter, that will be great.

**Comment by Xiaojieqiu** [comment]
Hi yifang, our monocle2/rge paper is online now (https://www.nature.com/nmeth/journal/vaop/ncurrent/full/nmeth.4402.html). Please check out the paper for the detailed explanation of parameters used in monocle (in the supplementary figure 13).
ncenter is the parameter for kmeans. if you want to see more branches. You should check the scree plot using plot_pc_variance_explained function and then choose proper dimension to reconstruct the principal tree. When we reconstruct the tree in high dimension we capture more variance of the data and thus can learn more detailed structure. we have two show cases in the monocle 2 paper to accurately learn complicate tree structure. please checkout the notebook from our monocle 2 website on how did we do that
