### ISSUE TITLE
How to use order_cells() non-interactively? 

### ISSUE THREAD

**Issue by fhermans27** [cole-trapnell-lab/monocle-release#410]
I recently started using monocle3 for pseudotime analysis. However, since I'm working on Jupyter on a computing cluster, I cannot use the order_cells() function interactively, and have to provide either root_pr_nodes or root_cells. 

In the documentation it is described that root_pr_nodes should be "NULL or a vector of starting principal points" (https://rdrr.io/github/cole-trapnell-lab/monocle3/man/order_cells.html). I am not sure how to provide this information, and how to find out what the root_pr_nodes are called, so I can provide this information. 

Any help is appreciated! 
Cheers,
Florian

**Comment by hpliner** [comment]
Hello,

This issue appears to be an issue about our new package, Monocle 3. Please post any issues for Monocle 3 to the monocle3 repository at https://github.com/cole-trapnell-lab/monocle3.

Monocle 3 Development team
