### ISSUE TITLE
setOrderingFilter in Monocle3

### ISSUE THREAD

**Issue by pavsol** [cole-trapnell-lab/monocle-release#412]
Hello,
function setOrderingFilter is not available in monocle3. Is there any replacement of this or any alternative way how to set ordering genes?

Thank you,
Pavel

**Comment by hpliner** [comment]
Hello,

This issue appears to be an issue about our new package, Monocle 3. Please post any issues for Monocle 3 to the monocle3 repository at https://github.com/cole-trapnell-lab/monocle3.

Monocle 3 Development team

You can set ordering genes using the use_genes parameter in preprocess_cds. Run ?preprocess_cds for details
