### ISSUE TITLE
Looped trajectories

### ISSUE THREAD

**Issue by namitc** [cole-trapnell-lab/monocle-release#418]
Hi, 

I'm analyzing a dataset and am seeing a looped trajectory where a node branches off but later merges at another node to form a closed loop. Am I doing something wrong? I didn't do anything different from the tutorial. I'm not sure how to interpret this trajectory.

**Comment by 2019surbhi** [comment]
Hi, I think the default parameter for close_loop argument of learn_graph() is set to be TRUE. You can set it to FALSE to force non-looped branched trajectories when running this function
