### ISSUE TITLE
Error when using few genes

### ISSUE THREAD

**Issue by yang-william** [cole-trapnell-lab/monocle-release#44]
How many features/genes does monocle 2 need? When I used 8 genes, I received this error

![image](https://user-images.githubusercontent.com/23245419/29433371-e67c8dae-836c-11e7-8d32-710cad8a139e.png)

Thanks

**Comment by Xiaojieqiu** [comment]
note that estimateDispersions works on all genes (it basically use all genes to estimate a mean and variance relationship. please refer to the DESeq paper for details). Feature gene is a different thing. For Monocle 2 trajectory inference, feature genes which is selected by either supervise or non-supervised approach (like dpFeature) are often around 1k or so.

**Comment by yang-william** [comment]
So if my data only has a few genes (not feature genes), it wouldn't work?

**Comment by Xiaojieqiu** [comment]
no. it cannot robustly and accurately estimate a mean variance relationship with a few genes.

**Comment by yang-william** [comment]
Okay thank you.
