### ISSUE TITLE
Error in reduceDimension()

### ISSUE THREAD

**Issue by martaint** [cole-trapnell-lab/monocle-release#45]
Hi,

I get this error when running 
`count_matrix <- reduceDimension(count_matrix, max_components = 2,
                        reduction_method = 'tSNE', verbose = T)`

Remove noise by PCA ...
You're computing too large a percentage of total singular values, use a standard svd instead.Reduce dimension by tSNE ...
Fehler in Rtsne.default(as.matrix(topDim_pca), dims = max_components, pca = F,  : 
  Perplexity is too large.

I have absolutely no idea how to fix it and why it happens. I would be grateful for any help!

**Comment by Xiaojieqiu** [comment]
If you are trying to run tSNE for visualizing cell clusters. max_components should be normally larger than 2. You can check that with the scree plot (see the plot_pc_variance_explained function). Normally we use about 15 top PCA components for tSNE dimension reduction. Perplexity is a parameter used in tSNE (“perplexity,” which says (loosely) how to balance attention between local and global aspects of your data.). Check this website for an intuitive understanding of tSNE if you are interested : 
https://distill.pub/2016/misread-tsne/

**Comment by martaint** [comment]
Thank you very much, 
the link is very interesting!

**Comment by sudhantt** [comment]
Hello, Did you find the solution for Err: Perplexity is too large ? I stuck in it. What is the change should I make in the code?

**Comment by martaint** [comment]
Hi, nope unfortunately I couldn't find a solution, but I have that error only when the number of cells is very very small. No idea how to fix it, so I tried to use another tool :)

**Comment by sudhantt** [comment]
HI,
Here is a solution , just added perplexity = 21 in the code, above 21only it gives error.


```
HSMM <- reduceDimension(HSMM, max_components = 2, num_dim = 3,
  norm_method = 'log',
  reduction_method = 'tSNE',
  verbose = T, perplexity = 21)
```

**Comment by BioLaoXu** [comment]
Try debugging the perplexity value size,less cells,the value will be smaller
