### ISSUE TITLE
monocle version 1

### ISSUE THREAD

**Issue by saralinker** [cole-trapnell-lab/monocle-release#48]
Is there an archived version of the original monocle code available? I recently upgraded to the new version and am trying to reproduce plots made previously for a comparison but the furthest back that I can find is 2.4.0. Any help would be much appreciated.

**Comment by Xiaojieqiu** [comment]
you can get old version of Monocle (or any other old version bioconductor packages) from this link: 
http://bioconductor.org/about/release-announcements/

see some discussion on the same question here: https://www.biostars.org/p/208115/
