### ISSUE TITLE
Code and documentation/vignette suggestion

### ISSUE THREAD

**Issue by mebbert** [cole-trapnell-lab/monocle-release#50]
Hi,

Loving Monocle. I have a small suggestion in the code and [documentation/vignette](http://cole-trapnell-lab.github.io/monocle-release/docs/). Perhaps I've misunderstood, so correct me if I'm wrong.

I noticed the call to estimate size factors and dispersion is buried at the bottom of a section [Converting TPM to mRNA counts](http://cole-trapnell-lab.github.io/monocle-release/docs/#converting-tpm-fpkm-values-into-mrna-counts-alternative) that not everyone needs. I skipped that section since I have UMI counts and proceeded with remaining sections, including differential expression. I assumed I had performed any required steps up to that point, and that any other necessary calculations were within the `differentialGeneTest` call. 

My suggestion would be to place the documentation for `estimateSizeFactors` and `estimateDispersions` in a more general location. I also think it would be helpful to add a warning or error if someone runs `differentialGeneTest` without running important steps prior.

Or, have I misunderstood something?

Really appreciate it!

**Comment by Xiaojieqiu** [comment]
Hi mebbert, 

Thanks a lot for your comment, that is right, descriptions about `estimateSizeFactors` and `estimateDispersions` should be moved to a more general place. We will update this to our online vignettee soon
