### ISSUE TITLE
Extract normalized expression matrix

### ISSUE THREAD

**Issue by mebbert** [cole-trapnell-lab/monocle-release#51]
Hi,

I'm working with 10x Genomics UMI data. I'd like to extract Monocle's normalized expression matrix so I can make custom expression plots, etc. Calling `exprs(<cds>)` only returns the original matrix, as far as I can tell. 

Is there a quick way to extract the normalized matrix?

Really appreciate your help.

**Comment by Xiaojieqiu** [comment]
If you mean the `normalized matrix` by the size factor normalized matrix, you can just divide each gene in each cell by the corresponding size factor to get the normalized matrix, see the example below: 
```
lung <- load_lung()
 t(t(exprs(lung)) /  pData(lung)[, 'Size_Factor'])
```

**Comment by mebbert** [comment]
Ah, perfect. Thank you for such a quick response.

**Comment by wasqqdyx** [comment]
@Xiaojieqiu

**Comment by wasqqdyx** [comment]
@Xiaojieqiu Thanks, but I wonder whether this converted matrix refers to "TPM"?

**Comment by Xiaojieqiu** [comment]
@wasqqdyx this converted matrix is not "TPM" but a size factor normalized matrix. to get TPM from FPKM, you can use this formula   
`TPM <- esApply(standard_cds, 2, function(x) x / sum(x) * 10^6)`

**Comment by balthasar0810** [comment]
But Monocle seems to work with some kind of normalised counts. You see this when gene expression is plotted over pseudotime. It is called relative expression. Is this stored somewhere?

**Comment by penglbio** [comment]
I want to get the normalized expression matrix. But I want to know when we use plot_gene_in_psuedotime process, did we used the normalized expression matrix. But why in our code, you selected the integer to plot the figure when the expressionFamily is negbinomial.size or  negbinomial. If I want to use the normalized expression table, should I convert the data the integer?

**Comment by pbpayal** [comment]
is the Size Factor normalization across all clusters in one sample or all samples?
