### ISSUE TITLE
Question re BEAM

### ISSUE THREAD

**Issue by tramdoan** [cole-trapnell-lab/monocle-release#53]
Hi,

I would like some clarification on the BEAM algorithm. If I have a Monocle trajectory that consists of a Stem population branching at branch point 1 into two distinct lineages L1 and L2 (within each of the L1 and L2 lineages, there are further subsequent branch points and states). If I specify branch point 1 in a BEAM analysis, does BEAM consider only the cells in the 3 immediate adjacent states to branch point 1 or does it consider the entire of the L1 and L2 lineages in the analysis ? Thanks.

**Comment by Xiaojieqiu** [comment]
If you specify a branch point, BEAM will take all descendants of that branch point from two lineages (including subsequent branch points, cells, etc) and the progenitor states to test for lineage-specific genes. If you want to only test for branch genes between the cells on the immediate states of the branch point, you can use the branch_states argument and pass the pair of states after the branch point to test for branch genes.

**Comment by Xiaojieqiu** [comment]
I suppose this issue has been resolve. I am closing the issue now.
