### ISSUE TITLE
clusterCells results

### ISSUE THREAD

**Issue by igordot** [cole-trapnell-lab/monocle-release#55]
I just started using Monocle and am going through all the basic commands. I am trying to understand `clusterCells()` output.

The first issue is easy. The `num_clusters` parameter seems to generate 1 less than requested. For example, if I set it to 5, I will get 4 clusters. Is that a problem?

The second issue might be more complicated. Here is an example (generated with `clusterCells(cds, num_clusters = 8 + 1)`):
![image](https://user-images.githubusercontent.com/6363505/31740664-ffe48a9c-b41f-11e7-9bf2-0adf6468bdc1.png)
I am not sure why I am getting those clusters. Specifically, the red and orange clusters can be clearly split into multiple subpopulations. I previously analyzed the same cells with different tools, so I have an idea of what they all are. The main big cluster is complicated, but the small clusters are distinct subpopulations. Regardless of how well tSNE worked, they should be easily separable by any method. Do you have any theories on why they are classified as part of the red or orange clusters? Does that seem reasonable?

**Comment by Xiaojieqiu** [comment]
Hi @igordot have you updated your monocle package to version 2.6.1? there was bug in detecting the clusters in version 2.6.0 and was fixed recently in the version 2.6.1. Please let me know if you still have the problem once you update Monocle

**Comment by crisgiu** [comment]
Upgraded BioC to 3.6 (within R-3.4.0 w/ irlba_2.2.1) & updated monocle to 2.6.1.
Still having the same problem as _igordot_:
`HSMM_PGC <- clusterCells(HSMM_PGC, num_clusters=8)`
-> outputs 7 clusters

**Comment by LEMH** [comment]
I am also experiencing the same problem with Monocle v2.6.3: when the requested number of clusters is 9 or more, I get the desired number of clusters. But when num_clusters<9, the number of clusters is one less than requested.

**Comment by novikovdan** [comment]
I am experiencing the same problem with monocle_2.6.4 :(

**Comment by Wanvdphelys** [comment]
I am experiencing the same problem with monocle_2.8.0

**Comment by CodeInTheSkies** [comment]
Hello!

Any resolution to this?  I am experiencing the same problem of one less cluster than specified.  Any responses would be greatly appreciated!

Thanks.

**Comment by yingyonghui** [comment]
Hello all,

I am experiencing the same problem with monocle_2.10.1.
Is there any suggestions?

Thanks.
