### ISSUE TITLE
maybe a bug ?

### ISSUE THREAD

**Issue by bahengxing** [cole-trapnell-lab/monocle-release#58]
Hi guys!

I used monocle_2.6.0 ro tun 10xgenomics data matrix and it run an err as follow:

could you please help me to solve it?

thank you

library(monocle)
library(cellrangerRkit)
cellranger_pipestance_path <- "/appdata/apcell/Ovir2"
gbm- load_cellranger_matrix(cellranger_pipestance_path)

fd <- fData(gbm)
colnames(fd)[2] <- "gene_short_name"
HSMM<- newCellDataSet(exprs(gbm),
                          phenoData = new("AnnotatedDataFrame", data = pData(gbm)),
                          featureData = new("AnnotatedDataFrame", data = fd),
                          lowerDetectionLimit = 0.5,
                          expressionFamily = negbinomial.size())
HSMM <- estimateSizeFactors(HSMM)
HSMM <- estimateDispersions(HSMM)
disp_table <- dispersionTable(HSMM)
unsup_clustering_genes <- subset(disp_table, mean_expression >= 0.1)
HSMM <- setOrderingFilter(HSMM, unsup_clustering_genes$gene_id)
plot_ordering_genes(HSMM)
plot_pc_variance_explained(HSMM, return_all = F) 

**Error in (function (A, nv = 5, nu = nv, maxit = 100, work = nv + 7, reorth = TRUE,  : 
  BLAS/LAPACK routine 'DLASCL' gave error code -4**

**Comment by Xiaojieqiu** [comment]
Hi please check this google forum thread. 
https://groups.google.com/forum/#!topic/monocle-users/PknSY5VOTF4

This comes from a bug from the irlba package.

**Comment by bahengxing** [comment]
font{
        line-height: 1.7;
    }


    
Hi, xiaojieThank you for your link, but i can not open it (GOOGLE is blocked) in China.Would you like please paste it in email?Best regards!



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    On 11/2/2017 13:10，Xiaojie Qiu<notifications@github.com> wrote： 


Hi please check this google forum thread.
https://groups.google.com/forum/#!topic/monocle-users/PknSY5VOTF4
This comes from a bug from the irlba package.

**Comment by Xiaojieqiu** [comment]
Copy from google groups 
Hi there, 

I believe the errors reporting here relates to some new bugs introduced in irlba package. 
Can you guys try to install the newest irlba package from their github repo. 

See the issue I reported here: 
https://github.com/bwlewis/irlba/issues/25

The Irlba package authors is planning to release those change to CRAN pretty soon too. 
I have tested your code and it went through nicely. 
(Also, we are planning to release by the end of this week.  Although I am sure the issue here can be resolved by simply update the irlba package)
- show quoted text -

**Comment by bahengxing** [comment]
font{
        line-height: 1.7;
    }


    
I downloaded  irlba-master package version 2.3.2 from github repo and install it , but this error still happened.Best regards!



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    On 11/2/2017 18:50，Xiaojie Qiu<notifications@github.com> wrote： 


Copy from google groups
Hi there,
I believe the errors reporting here relates to some new bugs introduced in irlba package.
Can you guys try to install the newest irlba package from their github repo.
See the issue I reported here:
bwlewis/irlba#25
The Irlba package authors is planning to release those change to CRAN pretty soon too.
I have tested your code and it went through nicely.
(Also, we are planning to release by the end of this week.  Although I am sure the issue here can be resolved by simply update the irlba package)

show quoted text -

**Comment by bahengxing** [comment]
font{
        line-height: 1.7;
    }


    
Hi xiaojieSorry, I am little careless.It is now working well when I restart Rstudio.Thank you for your help very much!Best regards!



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    On 11/2/2017 18:50，Xiaojie Qiu<notifications@github.com> wrote： 


Copy from google groups
Hi there,
I believe the errors reporting here relates to some new bugs introduced in irlba package.
Can you guys try to install the newest irlba package from their github repo.
See the issue I reported here:
bwlewis/irlba#25
The Irlba package authors is planning to release those change to CRAN pretty soon too.
I have tested your code and it went through nicely.
(Also, we are planning to release by the end of this week.  Although I am sure the issue here can be resolved by simply update the irlba package)

show quoted text -
