### ISSUE TITLE
Importing Seurat object - error using importCDS

### ISSUE THREAD

**Issue by CodeInTheSkies** [cole-trapnell-lab/monocle-release#59]
Hello Monocle Team,

I know this is just out, but I tried to import a Seurat object into monocle using importCDS, but I'm getting the following error:

Error in newCellDataSet(data, phenoData = pd, featureData = fd, lowerDetectionLimit = lowerDetectionLimit,  : 
  Error: argument cellData must be a matrix (either sparse from the Matrix package or dense)

Is this known, and will a fix be available?  Or has this already been fixed in the dev version?

Alternatively, at this time, am I better off using just the data matrix and manually creating the monocle object using newCellDataSet until things become a bit more stable with all these new releases?

Any pointers would be greatly appreciated!

Thanks.

**Comment by Xiaojieqiu** [comment]
Hi there, could you please tell me what is the class of the raw data stored in your Seurat object by using class(seurat_obj@raw.data)?

**Comment by CodeInTheSkies** [comment]
Thanks for responding.  The class is a data frame  (data.frame).

**Comment by Xiaojieqiu** [comment]
I see the issue. When I wrote the code, I assumes that slot is either a matrix or a sparseMatrix. My bad. The monocle CDS only accepts the matrix or a sparseMatrix. you may try to change that slot to matrix or if it is big, change to a sparsematrix. for example: 
class(seurat_obj@raw.data) <- "data.frame"

then the importCDS function should work. I will fix that

**Comment by CodeInTheSkies** [comment]
OK, thanks!  Will try that.

By the way, I just opened another issue regarding "plot_pc_variance_explained".  Any pointers/thoughts would be very much appreciated!

**Comment by CodeInTheSkies** [comment]
Still doesn't work, because the situation where the "data" slot and the "raw.data" slot have different numbers of columns seems to be a problem.  This mismatch is accepted within Seurat, because typically, one would do further filtering of the data that might result in a reduced number of cells in the data slot compared to the raw.data slot.  So, somewhere in your code, I think you might have to address this mismatch appropriately.  Just my two cents, if this makes sense.

The error I am getting is the following:

Error in `[[<-.data.frame`(`*tmp*`, i, value = c(NA_real_, NA_real_, NA_real_,  : 
  replacement has 397 rows, data has 387

My raw.data has 397 cells, but upon further filtering in Seurat downstream, my data slot becomes shorter in terms of the number of cells.

I used the code:

`pbmc_copy@raw.data <- as.matrix(pbmc_copy@raw.data)
mono_cds <- importCDS(pbmc_copy, import_all = FALSE)`

**Comment by graddi** [comment]
Hello, I am having the same issues. Tried running both the standard code on your page and the code of above but I get the same mismatch of cell numbers. Was there any progress in fixing the issue? Thank you for your time and efforts! 

> aggrtotman@raw.data <- as.matrix(aggrtotman@raw.data)
> aggr.mono <- importCDS(aggrtotman, import_all = TRUE)
Error in `[[<-.data.frame`(`*tmp*`, i, value = c(NA_real_, NA_real_, NA_real_,  : 
  replacement has 5333 rows, data has 5292

**Comment by Xiaojieqiu** [comment]
great! that is what I did for the 2.6.1.
