### ISSUE TITLE
"plot_pc_variance_explained" keeps throwing "did not converge" warning

### ISSUE THREAD

**Issue by CodeInTheSkies** [cole-trapnell-lab/monocle-release#60]
Hello there, 

I am using a manually created monocle object (i.e., not importing from Seurat or scater) and many of the steps explained in the monocle tutorial work well until I come to "plot_pc_variance_explained".  This function keeps throwing the following warning:

Warning in (function (A, nv = 5, nu = nv, maxit = 100, work = nv + 7, reorth = TRUE,  :
  did not converge--results might be invlaid!; try increasing work or maxit

I have tried increasing maxit upto 10000, and have also set fastpath=FALSE to no avail.

I just realized that I am using the RSEM "expected count" values as the data matrix.  This, I believe, are raw count values.  I saw the note in the tutorial that monocle best likes TPM or FPKM values, and I am in the process of changing the input matrix to one with those values.  Would that solve the problem?

Any guidance/pointers would be greatly appreciated.

Thanks a lot!

**Comment by Xiaojieqiu** [comment]
please install the newest irlba package from github (https://github.com/bwlewis/irlba/) to see whether or not this issue disappears.
