### ISSUE TITLE
rho and delta theshold values

### ISSUE THREAD

**Issue by sudhirthakurela** [cole-trapnell-lab/monocle-release#61]
Hi,

Can you please elaborate on how do you decide rho and delta threshold values based on rho vs. delta plot? 

ST

**Comment by Xiaojieqiu** [comment]
in the decision plot, `rho` means local density of that while `delta` means the distance of the current cell to another cell with higher density. Therefore the `outliers` on the decision plot normally corresponds to the density peaks. You would like to select relative high values of rho and delta as the threshold to get those `outliers`.

In addition, in Monocle 2.6.1, we provide a knn-network based clustering method which used by Seurat, phenograph and other packages (you can set `method = "louvain"`) . It normally returns more clusters but performs much faster and can deal with large datasets.
