### ISSUE TITLE
Pairwise differential expression analysis

### ISSUE THREAD

**Issue by sudhirthakurela** [cole-trapnell-lab/monocle-release#62]
Hi,

I couldn't find but may I know if there a way to do a pairwise differential expression analysis between clusters or one cluster against a group of clusters? It will also be helpful if you can add columns in "differentialGeneTest" to show which cluster that gene is up or down-regulated.

ST

**Comment by dpcook** [comment]
There are a few issues that were opened a while ago about implementing easy ways to pull out effect sizes/fold changes (see #6  and #7), but to my knowledge they haven't been put in yet. Fold changes between clusters can be computed relatively easily from the expression matrix and dumped into your results table, but I'm guessing you're interested in getting a p-value associated with each pairwise comparison too. You could bounce your data over to DESeq2 or something else and use contrasts for each comparison.

**Comment by sudhirthakurela** [comment]
Thanks a lot.
I actually did some similar. I performed differential analysis by subsetting cds to get only interested clusters.

DEG_Clust_2_1 <- differentialGeneTest(sc_Monocle[expressed_genes, pData(sc_Monocle)$Cluster %in% c(2, 1)], fullModelFormulaStr="~Cluster", cores = 10)

 and then merged that with population level expression matrix to get fold change for DEG. 

Thanks again.

ST

**Comment by ravipatel4** [comment]
Hi @sudhirthakurela,
Can you please explain how you obtained population level expression matrix? Is there a function in Monocle package to do that or you calculated the fold changes by yourself?
Thank you.
