### ISSUE TITLE
Error when running plot_pc_variance_explained

### ISSUE THREAD

**Issue by miketerkelsen** [cole-trapnell-lab/monocle-release#64]
When I try to plot the variance explained by each component the following error presents itself:

Error in (function (A, nv = 5, nu = nv, maxit = 100, work = nv + 7, reorth = TRUE,  : 
  BLAS/LAPACK routine 'DLASCL' gave error code -4

I can´t figure out what causes this error.

**Comment by bapoorva** [comment]
I have this same error. Did you figure out why this is happening or how to fix it ?

**Comment by miketerkelsen** [comment]
Yes, I did solve the problem in my case at least. 

The problem seems to lie with the irlba package. The error has been corrected but not published to CRAN yet so what I did was to install the master from github through utilization of devtools and the install_github function by typing `install_github("bwlewis/irlba")`.

I hope this helps you.

**Comment by bapoorva** [comment]
That is helpful. Thank you very much

**Comment by miketerkelsen** [comment]
You´re very welcome.

**Comment by leonard9338** [comment]
Hello,

I switch from monocle 2.4 to monocle 2.8 and I noticed that the normalization method by default was changed from "vstExprs" to "log". When I tried to reproduced my results in monocle 2.8 by setting norm_method to  "vstExprs", it gives me the same error as above:

```
plot_pc_variance_explained(gbm_cds,verbose = T,norm_method='vstExprs')
Error in (function (A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE,  : 
  BLAS/LAPACK routine 'DLASCL' gave error code -4

```
When I was on monocle 2.4 a few month ago I fixed it as explained above but now it does not work even after installing irlba from github.

There is no error with log normalization. Do you know how to fix it ?

Thanks
