### ISSUE TITLE
BEAM Warning

### ISSUE THREAD

**Issue by CodeInTheSkies** [cole-trapnell-lab/monocle-release#66]
Hi there,

I am running BEAM, and my data is such that there is just one branch point with two resulting branches or lineages.

I get this warning:

Warning messages:
1: In if (progenitor_method == "duplicate") { :
  the condition has length > 1 and only the first element will be used
2: In if (progenitor_method == "sequential_split") { :
  the condition has length > 1 and only the first element will be used

Could somebody explain what this means, and is this crucial, or can it be ignored?

Thanks!

**Comment by Xiaojieqiu** [comment]
BEAM supports two methods for dealing with the progenitor methods: one is `duplicate` which will duplicate all the progenitor cells and assign to each of the downstream lineages. The second is the `sequential_split` which will put the cells with the even pseudotime ordering to one branch and the odd pseudotime ordering into another branch. 
By default, it uses the `duplicate`

**Comment by CodeInTheSkies** [comment]
Thanks for your answer, but I still am not very sure whether I can ignore this, or should I fix it somehow?

**Comment by Xiaojieqiu** [comment]
no you can ignore it and the BEAM will use the default "duplicate" option
