### ISSUE TITLE
"plot_pc_variance_explained" and "plot_cell_clusters" functions missing in monocle 2.6.0

### ISSUE THREAD

**Issue by bapoorva** [cole-trapnell-lab/monocle-release#67]
Hi,
I know this issue has been raised before and the solution was to install the newer version of monocle locally, which i did. I currently have monocle 2.6 which is the most recent release and the functions "plot_pc_variance_explained" and "plot_cell_clusters" aren't there. Is there a new function instead of these ?

AB

**Comment by Xiaojieqiu** [comment]
It should be there. you can check the Reference Manual and it shows that both functions are there: 

http://bioconductor.org/packages/release/bioc/manuals/monocle/man/monocle.pdf

**Comment by bapoorva** [comment]
Sorry my bad. because I installed it locally, there were two versions of monocle and the function was using monocle 2.0 by default.
