### ISSUE TITLE
BEAM Error

### ISSUE THREAD

**Issue by CodeInTheSkies** [cole-trapnell-lab/monocle-release#69]
Hello All,

Does anyone know why this BEAM error occurs, and how to deal with it?

<simpleError in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,     Ym2 = Ym2, etastart = etastart, mustart = mustart, coefstart = coefstart,     family = family, control = control, constraints = constraints,     extra = extra, qr.arg = qr.arg, Terms = mt, function.name = function.name,     ...): could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.>

I am still able to complete the run and do the subsequent Heatmap, but I don't understand the error and whether there is a concern.

Any insights would be great!

Thanks.

**Comment by CodeInTheSkies** [comment]
Just wondering, any insights on this?

**Comment by Xiaojieqiu** [comment]
this error happens when the vglm fitting procedure used in BEAM function failed to fit spline curves for the gene expression across two lineages (in cases where the gene in your data is very sparse, etc). The BEAM result for that gene  will normally has status FAIL.
