### ISSUE TITLE
differentialGeneTest q-values

### ISSUE THREAD

**Issue by CodeInTheSkies** [cole-trapnell-lab/monocle-release#70]
Just a quick question:

How are the qvals computed in the output of differentialGeneTest?  Are they BH-corrected, or Bonferroni?  It will be great if somebody can tell me the specific type of the q-values.

Thanks a lot.

**Comment by dpcook** [comment]
Hey CodeInTheSkies. qvals are computed using p.adjust(pvals, method="BH"). If looking for more details, check out differential.expression.R file in the monocle-release/R/ folder

**Comment by CodeInTheSkies** [comment]
Thanks!
