### ISSUE TITLE
plot_pseudotime_heatmap handling of gene ID

### ISSUE THREAD

**Issue by topherconley** [cole-trapnell-lab/monocle-release#71]
When calling `plot_pseudotime_heatmap`, the function does not appear to robustly handle the case when there are two or more Ensembl IDs that map to the same `gene_short_name` attribute. In such a case, the `pheatmap` stage fails and complains of duplicate row names. Is it possible to handle this scenario without having do an external hack like renaming the duplicate `gene_short_name` entries to something like SYM-1, SYM-2?

**Comment by Xiaojieqiu** [comment]
I think you may also be able to easily identify those genes with duplicated gene_short_name in fd data and change it unique values before running `plot_pseudotime_heatmap`
