### ISSUE TITLE
BEAM's output - meaning of "use_for_ordering"

### ISSUE THREAD

**Issue by CodeInTheSkies** [cole-trapnell-lab/monocle-release#73]
Hi there,

What exactly is the meaning of the TRUE/FALSE column named "use_for_ordering" in BEAM's output?

I first use the most differentially expressed set of genes (top 1000) among the clusters to order the cells.  Then call BEAM at one of the branch points.

I don't understand the column  "use_for_ordering".

Any explanation would be great!

Thanks.

**Comment by dpcook** [comment]
If I recall, the rows of that column that == TRUE should match the 1000 differentially expressed genes you used to order the cell then.

**Comment by Xiaojieqiu** [comment]
the `use_for_ordering` from the output of BEAM is the same as that in the data frame returned by `fData(cds)`. @dpcook  is right that in your case it should just match up with the 1k top differentially expressed genes you used for ordering the cells.
