### ISSUE TITLE
How to find genes in the same cluster after running "plot_pseudotime_heatmap" command?

### ISSUE THREAD

**Issue by J-sara** [cole-trapnell-lab/monocle-release#76]
Hello,

I have used "plot_pseudotime_heatmap" to find genes that change as a function of pseudotime. Because I have several genes (around 1000 genes) on the heatmap, the name of the genes that cluster together is not readable. How I can find the name of the genes that cluster together on the heatmap? 
Using "return_heatmap =TRUE" argument gives an object that includes the gene names on the heatmap but is not still obvious which one are clustered together. I want to perform GO term analysis on the genes that follow a similar pattern during the pseudotime.

Best

**Comment by dpcook** [comment]
Hey J-sara,

Like you said, return_heatmap creates a pheatmap object, which stores the clustered tree is stored in $tree_row, so you can return the clusters with the cutree function on that:
`t <- plot_pseudotime_heatmap(x, return_heatmap=T)`
`t <- as.data.frame(cutree(t$tree_row, k=3)`
`colnames(t) <- "Cluster"`
`t$Gene <- rownames(t)`

Just be sure to change k=n to match the number of clusters in the heatmap.

Then you can use dplyr::filter on that data frame to get genes associated with each cluster, or you can write it out to a csv and do whatever you want with it

**Comment by Xiaojieqiu** [comment]
thanks @dpcook !

**Comment by NicolasHipp** [comment]
Hi monocle team!

I followed this post to extract gene names which are in the same cluster. 
`toto1<-plot_pseudotime_heatmap(HSMM[rownames(fData(HSMM))[rownames(fData(HSMM))%in%ESNGtot],],
                              num_clusters = 5,norm_method = "log", cores = 8, return_heatmap = T)`
<img width="560" alt="image" src="https://user-images.githubusercontent.com/18481923/48487228-ddf02a80-e81d-11e8-8f7f-83137bebd7f5.png">

I used cutree
toto1_cluster<-as.data.frame(cutree(toto$tree_row, k=5))
length(rownames(toto1_cluster)[toto1_cluster$Genes ==1])
549
rownames(toto1_cluster)[toto1_cluster$Genes ==2]
930
rownames(toto1_cluster)[toto1_cluster$Genes ==3]
299
rownames(toto1_cluster)[toto1_cluster$Genes ==4]
695
rownames(toto1_cluster)[toto1_cluster$Genes ==5]
693

Interestingly, the number of genes in each cluster doesn't seems to fit with the dendrogram representation. 
Does anybody know what is going on?

Thanks for the help,
nicolas

**Comment by honghh2018** [comment]
Hi @dpcook 
     The cutree function that set k parameter same as plot_pseudotime_heatmap's num_clusters result showing variable clustering compared with the result of  plot_pseudotime_heatmap showing.
      What happen to this ?
       and how to fix it ?
       any advice would be appreciated.
