### ISSUE TITLE
Subsetting data based on sampleNames or varLabels

### ISSUE THREAD

**Issue by Gorman222** [cole-trapnell-lab/monocle-release#77]
I am trying to subset my data based on a vector of sample names, but I cannot accomplish it.
I have tried:
**x@phenoData$sampleNames <- example.cells**  
but I am getting this error:
**replacement has 661 rows, data has 5809**
The object I am trying to subset is a Cell Data Set created from a Seurat object by the importCDS function.
I have also assigned a Cell Type to every sample that is called "CellType" which is part of the meta.data of the Seurat object and is listed under the varLabels slot of the phenoData after it is converted to a CDS.
I would like help subsetting based on either of these variables, thank you.

**Comment by dpcook** [comment]
Hey Gorman,

The code you tried is attempting to add/replace a column in phenoData with your example.cells variable, but this variable is only 661 entries long, while phenoData has 5809 rows, hence the error.

To subset your CellDataSet (x), you should simply be able to go
`x.subset <- x[,example.cells]`
Assuming your example.cells variable match the rownames of phenoData, or the appropriate numerical index.

Similarly, you can subset genes with
`x.subset <- x[example.genes,]`

Also, not directly related, you may be interested to know that with monocle loaded, you can access phenoData several ways that are a little easier to write out than x@phenoData$someColumn
`pData(x)$someColumn`
`x$someColumn`
both work

**Comment by Gorman222** [comment]
Thank you very much for your help dpcook.

**Comment by mengchengyao** [comment]
> Hey Gorman,
> 
> The code you tried is attempting to add/replace a column in phenoData with your example.cells variable, but this variable is only 661 entries long, while phenoData has 5809 rows, hence the error.
> 
> To subset your CellDataSet (x), you should simply be able to go
> `x.subset <- x[,example.cells]`
> Assuming your example.cells variable match the rownames of phenoData, or the appropriate numerical index.
> 
> Similarly, you can subset genes with
> `x.subset <- x[example.genes,]`
> 
> Also, not directly related, you may be interested to know that with monocle loaded, you can access phenoData several ways that are a little easier to write out than x@phenoData$someColumn
> `pData(x)$someColumn`
> `x$someColumn`
> both work

Hey dpcook,
I subset my data by your method(x.subset <- x[,example.cells]), it works well. However, I got an error  with "Error: Column `sample_state` must be length" when plot cell trajectory by function of plot_cell_trajectory, do you why or do you get the same error?

**Comment by mengchengyao** [comment]
> > Hey Gorman,
> > The code you tried is attempting to add/replace a column in phenoData with your example.cells variable, but this variable is only 661 entries long, while phenoData has 5809 rows, hence the error.
> > To subset your CellDataSet (x), you should simply be able to go
> > `x.subset <- x[,example.cells]`
> > Assuming your example.cells variable match the rownames of phenoData, or the appropriate numerical index.
> > Similarly, you can subset genes with
> > `x.subset <- x[example.genes,]`
> > Also, not directly related, you may be interested to know that with monocle loaded, you can access phenoData several ways that are a little easier to write out than x@phenoData$someColumn
> > `pData(x)$someColumn`
> > `x$someColumn`
> > both work
> 
> Hey dpcook,
> I subset my data by your method(x.subset <- x[,example.cells]), it works well. However, I got an error with "Error: Column `sample_state` must be length" when plot cell trajectory by function of plot_cell_trajectory, do you why or do you get the same error?

I found how to solve this problem，just do as follow，
h<-HSMM_myo[,example.cells]
h@reducedDimS<-h@reducedDimS[,example.cells]
