### ISSUE TITLE
Error in if (tol * ans$d[1] < eps): missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by exin11** [cole-trapnell-lab/monocle-release#78]
Hi there,

I'm running Monocle to analyze my 10X data. When I tried to run: 
my_cds <- reduceDimension(my_cds, max_components = 2, num_dim = 5,
                          reduction_method = 'tSNE', verbose = TRUE)
I got this error:
Error in if (tol * ans$d[1] < eps) warning("convergence criterion below machine epsilon") : 
  missing value where TRUE/FALSE needed

Can anyone help me to fix it? Thanks.
> packageVersion('monocle')
[1] ‘2.6.1’

**Comment by jebard** [comment]
I also ran into this same problem with 10x data

**Comment by Xiaojieqiu** [comment]
Can you try to update irlba (see this closed issue: https://github.com/cole-trapnell-lab/monocle-release/issues/58) and also try to increase `num_dim` to like 25 or more for doing tSNE dimension reduction on 10x data?

**Comment by exin11** [comment]
Thanks, Xiaojie,

I updated irlba (2.3.1) and increased num_dim to 20. This error was resolved, but I got another one:

Error in (function (A, nv = 5, nu = nv, maxit = 100, work = nv + 7, reorth = TRUE,  : 
  BLAS/LAPACK routine 'DLASCL' gave error code -4

I think this is from irlba, and I tried to use 'fastpath=FALSE', but cannot fix it...
Do you know how to resolve it? Thank you so much!

Best,
Kun

**Comment by exin11** [comment]
Hi Xiaojie,
I updated the irlba package, and the version is: 2.3.1. Is this OK?>
Best,
Kun

**Comment by Xiaojieqiu** [comment]
it should be 2.3.2 if you install from the github repo

**Comment by exin11** [comment]
Thanks, Xiaojie,
I installed from github, now it's 2.3.2. And it works, thank you so much.

best,
kun
