### ISSUE TITLE
How to save a CellDataSet

### ISSUE THREAD

**Issue by Gorman222** [cole-trapnell-lab/monocle-release#82]
The reduceDimension function is very time consuming, and I would like to save the resulting CellDataSet so I may load it later.  
What file extension should I use for the save function?
I've tried to save it as a .RobJ but the file then fails to load.
Thanks in advance for any assistance.

**Comment by dpcook** [comment]
Hey Gorman,

You can save it out as an RDS file that you can load up pretty easily:
`saveRDS(cds, file="/path/to/project/cds.rds")`

When you want to load it back up:
`cds <- readRDS("/path/to/project/cds.rds")`

**Comment by Gorman222** [comment]
Great, thank you!
