### ISSUE TITLE
Can monocle set multiple root_states?

### ISSUE THREAD

**Issue by garfieldyc** [cole-trapnell-lab/monocle-release#83]
My samples have two starting root_states. I am wondering if there is any strategy to deal with this situation.

Thanks in advance.

**Comment by Xiaojieqiu** [comment]
Are you saying that your samples have two potential population of progenitors or the like? 
It doesn't really make sense to have an ordering of cells with two different root. But you may order the cell by two root_states separately using orderCells function and do some downstream analysis with each root.
