### ISSUE TITLE
plot_genes_in_pesudotime: Error in model_expectation[x$f_id, x$Cell] : subscript out of bounds

### ISSUE THREAD

**Issue by miketerkelsen** [cole-trapnell-lab/monocle-release#84]
Every time I try to plot_genes_in_pseudotime I get the error:

"Error in model_expectation[x$f_id, x$Cell] : subscript out of bounds"

without any prior errors and I can't seem to find the cause.

**Comment by Xiaojieqiu** [comment]
It seems like the cds you passed in doesn't have the `gene_short_name` column in the fData. Can you verify this? (using `head(fData(cds))`)

**Comment by miketerkelsen** [comment]
Sorry, but thats not it.

**Comment by miketerkelsen** [comment]
These are the commands I input:

`to_be_tested <- row.names(subset(fData(Lrat_cluster1), gene_short_name %in% c("Col1a1", "Lrat", "Lum")))`
`Lrat_HSC_subset_diff <- Lrat_HSC_state[to_be_tested,]`
`diff_test_pseu <- differentialGeneTest(Lrat_HSC_subset_diff, fullModelFormulaStr = "~sm.ns(Pseudotime)")`
`diff_test_pseu[,c("gene_short_name", "pval", "qval")]`
`plot_genes_in_pseudotime(Lrat_HSC_subset_diff, color_by = "State")`

When I do type in fData I get the three genes I have selected for.

**Comment by Xiaojieqiu** [comment]
which version of monocle are you using? the error `"Error in model_expectation[x$f_id, x$Cell] : subscript out of bounds"` happens when the gene short name (`f_id`) or the cell (`Cell`)  is not in the cds. I never see such an error before. If you can share a sample data for me reproduce the result , I can help you take to take a look.

**Comment by miketerkelsen** [comment]
Could it be that the column with cell names is called V1 and not Cell? If not I will supply you with a link when I have access to a computer.

**Comment by miketerkelsen** [comment]
I have exported the objects needed to produce the error. Thanks in advance!
https://drive.google.com/file/d/14RzjpqZPDXfxXiyVkaSuK6_HA4R8eUzT/view?usp=sharing

**Comment by miketerkelsen** [comment]
Okay so changing the column name solved the problem however now I'm getting this error instead
Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column

**Comment by Xiaojieqiu** [comment]
I looked the data you posted previously. I found that both of the row names and columns for your cds are numbers: 
```> exprs(Lrat_HSC_subset_diff)[, 1:5]
      11 25 30 38 39
5614   6  0 10  7 10
14966  5  1  5  4  3
20370  0  2  0  0  3```

Could you please set the row name and column for the cds to the `V1` in your data? 

```> pData(Lrat_HSC_subset_diff)[1:2, ]
                   V1    Library_ID Size_Factor num_genes_expressed Total_mRNAs
11 AAACGGGTCATCTGCC-1 Lrat_oil_aggr     1.21290                2104        4665
25 AACACGTAGTTTAGGA-1 Lrat_oil_aggr     1.20848                1922        4648
   Cluster peaks halo     delta      rho              CellType Pseudotime State
11       1 FALSE TRUE 0.7280852 66.95110 Hepatic stellate cell  0.4034753     1
25       3 FALSE TRUE 0.3631547 59.39492 Hepatic stellate cell  7.9429222     4```

```> fData(Lrat_HSC_subset_diff)
                      V1 gene_short_name num_cells_expressed use_for_ordering
5614  ENSMUSG00000028003            Lrat                 745             TRUE
14966 ENSMUSG00000036446             Lum                 847             TRUE
20370 ENSMUSG00000001506          Col1a1                 641             TRUE```

**Comment by miketerkelsen** [comment]
Yeah, so as I wrote in the previous post I tried that and it did solve my problem. However now when plotting I get a staggered trend line but I can see another user is having the same problem so I will follow that post. Thanks for you time!

**Comment by ratbb** [comment]
hi , i met the same problem. how did you solve it?
