### ISSUE TITLE
Warning messages while running estimate dispersions

### ISSUE THREAD

**Issue by WhitneyFA** [cole-trapnell-lab/monocle-release#86]
Hello, 

I am using a larger 10X library and I am getting the following warnings after running estimate dispersions:

Removing 4 outliers
Warning messages:
1: Deprecated, use tibble::rownames_to_column() instead. 
2: glm.fit: algorithm did not converge 
3: glm.fit: algorithm did not converge 

Any advice on how to move forward?

Thank you

**Comment by Xiaojieqiu** [comment]
those warnings are fine and you can move forward for your downstream analysis. The first one is related to the tibble package and the second and third relates to the glm fitting procedure we used in estimating a function between mean and dispersion (by default, we set the fitting iteration to be 10 and if the fitting iteration is above 10, we will report this message). The mean-dispersion relation is only used as a hint of the dispersion parameters during the DEG test.
