### ISSUE TITLE
problem in plotting log transformed values in plot_pseudotime_heatmap 

### ISSUE THREAD

**Issue by sirusb** [cole-trapnell-lab/monocle-release#9]
Hi , 
First thank you for the great package. 
Just a small issue in `plot_pseudotime_heatmap` function when plotting the data in the log space.
The pseudo-count added to the values is set to `NA` at the fist line , which causes all the values to be `NA`
whichthrows an error.

Maybe just passe [this ](https://github.com/cole-trapnell-lab/monocle-release/blob/master/R/plotting.R#L927) line  `pseudocount <- NA`  to the arguments of the function.

**Comment by Xiaojieqiu** [comment]
Thanks for this catch!! I will fix this.

**Comment by Xiaojieqiu** [comment]
this has been addressed a while ago
