### ISSUE TITLE
Error: could not find function "importCDS"

### ISSUE THREAD

**Issue by muktad** [cole-trapnell-lab/monocle-release#97]
Hi!
I just downloaded the monocle using biocLite. And I am getting the error message mentioned in the subject line. I understand that this is a newer incorporation in 2.6.1, and Bioconductor seems to have that version as well so I am not sure where the problem is. When I call library('monocle'), I am not requested for any other dependencies meaning I have successfully installed all dependencies. Please help. If there are newer releases available can you point me to where they are? As it says 0 releases in git.

**Comment by muktad** [comment]
Problem solved by upgrading to R3.4.

**Comment by gturco** [comment]
I am also receiving this error, yet everything is up to the recommended updates.

Here is my `session_info()`, any ideas? 

`Session info -----------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       <NA>                        
 date     2018-03-07                  

Packages ---------------------------------------------
 package        * version date       source         
 assertthat       0.2.0   2017-04-11 CRAN (R 3.4.1) 
 base           * 3.4.1   2017-07-07 local          
 bindr            0.1     2016-11-13 CRAN (R 3.4.1) 
 bindrcpp         0.2     2017-06-17 CRAN (R 3.4.1) 
 Biobase        * 2.36.2  2017-05-04 Bioconductor   
 BiocGenerics   * 0.22.1  2017-10-07 Bioconductor   
 BiocInstaller  * 1.26.1  2017-09-01 Bioconductor   
 cluster          2.0.6   2017-03-10 CRAN (R 3.4.1) 
 colorspace       1.3-2   2016-12-14 cran (@1.3-2)  
 combinat         0.0-8   2012-10-29 CRAN (R 3.4.0) 
 compiler         3.4.1   2017-07-07 local          
 curl             3.1     2017-12-12 CRAN (R 3.4.3) 
 datasets       * 3.4.1   2017-07-07 local          
 DDRTree        * 0.1.5   2017-04-30 CRAN (R 3.4.0) 
 densityClust     0.3     2017-10-24 CRAN (R 3.4.2) 
 devtools       * 1.13.5  2018-02-18 CRAN (R 3.4.3) 
 digest           0.6.15  2018-01-28 CRAN (R 3.4.3) 
 dplyr            0.7.4   2017-09-28 CRAN (R 3.4.2) 
 fastICA          1.2-1   2017-06-12 CRAN (R 3.4.0) 
 FNN              1.1     2013-07-31 cran (@1.1)    
 ggplot2        * 2.2.1   2016-12-30 cran (@2.2.1)  
 ggrepel          0.7.0   2017-09-29 CRAN (R 3.4.2) 
 git2r            0.21.0  2018-01-04 CRAN (R 3.4.3) 
 glue             1.2.0   2017-10-29 CRAN (R 3.4.2) 
 graphics       * 3.4.1   2017-07-07 local          
 grDevices      * 3.4.1   2017-07-07 local          
 grid             3.4.1   2017-07-07 local          
 gridExtra        2.3     2017-09-09 CRAN (R 3.4.1) 
 gtable           0.2.0   2016-02-26 cran (@0.2.0)  
 HSMMSingleCell   0.110.0 2017-09-26 Bioconductor   
 httr             1.3.1   2017-08-20 CRAN (R 3.4.1) 
 igraph           1.1.2   2017-07-21 cran (@1.1.2)  
 irlba          * 2.3.2   2018-01-11 cran (@2.3.2)  
 knitr            1.20    2018-02-20 CRAN (R 3.4.3) 
 lattice          0.20-35 2017-03-25 CRAN (R 3.4.1) 
 lazyeval         0.2.1   2017-10-29 CRAN (R 3.4.2) 
 limma            3.32.10 2017-10-13 Bioconductor   
 magrittr         1.5     2014-11-22 CRAN (R 3.4.0) 
 Matrix         * 1.2-12  2017-11-15 CRAN (R 3.4.2) 
 matrixStats      0.53.1  2018-02-11 cran (@0.53.1) 
 memoise          1.1.0   2017-04-21 CRAN (R 3.4.0) 
 methods        * 3.4.1   2017-07-07 local          
 monocle        * 2.4.0   2017-04-25 Bioconductor   
 munsell          0.4.3   2016-02-13 cran (@0.4.3)  
 parallel       * 3.4.1   2017-07-07 local          
 pheatmap         1.0.8   2015-12-11 CRAN (R 3.4.0) 
 pillar           1.2.1   2018-02-27 CRAN (R 3.4.3) 
 pkgconfig        2.0.1   2017-03-21 CRAN (R 3.4.1) 
 plyr             1.8.4   2016-06-08 cran (@1.8.4)  
 qlcMatrix        0.9.5   2015-10-09 CRAN (R 3.4.0) 
 R6               2.2.2   2017-06-17 CRAN (R 3.4.1) 
 RColorBrewer     1.1-2   2014-12-07 cran (@1.1-2)  
 Rcpp             0.12.15 2018-01-20 cran (@0.12.15)
 reshape2         1.4.3   2017-12-11 cran (@1.4.3)  
 rlang            0.2.0   2018-02-20 CRAN (R 3.4.3) 
 rstudioapi       0.7     2017-09-07 CRAN (R 3.4.1) 
 Rtsne            0.13    2017-04-14 cran (@0.13)   
 scales           0.5.0   2017-08-24 CRAN (R 3.4.1) 
 slam             0.1-42  2017-12-21 cran (@0.1-42) 
 splines        * 3.4.1   2017-07-07 local          
 stats          * 3.4.1   2017-07-07 local          
 stats4         * 3.4.1   2017-07-07 local          
 stringi          1.1.6   2017-11-17 CRAN (R 3.4.2) 
 stringr          1.3.0   2018-02-19 CRAN (R 3.4.3) 
 tibble           1.4.2   2018-01-22 CRAN (R 3.4.3) 
 tools            3.4.1   2017-07-07 local          
 utils          * 3.4.1   2017-07-07 local          
 VGAM           * 1.0-5   2018-02-07 cran (@1.0-5)  
 withr            2.1.1   2017-12-19 CRAN (R 3.4.3)`
