### ISSUE TITLE
Monocle 2 R version:  R (>= 3.4) but R (>= 2.10.0)

### ISSUE THREAD

**Issue by evanbiederstedt** [cole-trapnell-lab/monocle-release#99]
Excellent software, documentation, and publication. 

Quick question on Monocle 2: 

The dependencies for Monocle 2 appears to be R 3.4 or higher (as detailed here: http://cole-trapnell-lab.github.io/monocle-release/docs/#installing-monocle )

However, this appears to be not the strictest of standards, as shown in the DESCRIPTION currently:
https://github.com/cole-trapnell-lab/monocle-release/blob/master/DESCRIPTION

`R (>= 2.10.0)`

What are the dependencies which will not work/not work correctly for (e.g.) R 3.3? Or is the R>=3.4  a suggestion based on the latest stable release of R?

**Comment by evanbiederstedt** [comment]
This is useful to know, as if it's required to port all pre-3.4 libraries which may be used in an analysis with Monocle2, labs should do this. If not, then 3.4 is not a requirement but a recommendation.

**Comment by Xiaojieqiu** [comment]
Hi @evanbiederstedt thanks for this question. R3.4 (or R3.5 for the next release shortly) is required because some depdent packages in Monocle are only built in R3.4 or R3.5.  We will update the description file in Monocle

**Comment by evanbiederstedt** [comment]
@Xiaojieqiu  Thanks for the help
